"use client";

import Link from "next/link";
import { Calendar, Copy, ListTodo } from "lucide-react";
import type { CommunicationLog, CommunicationStatus } from "@/lib/secretary/types";
import { SecretaryEntityDetailModal } from "@/components/secretary/SecretaryEntityDetailModal";
import { formatDateEl } from "@/lib/ui/child-labels";
import { CommunicationStatusBadge } from "./CommunicationStatusBadge";
import { CommunicationPriorityBadge } from "./CommunicationPriorityBadge";
import { useSecretaryTasks } from "@/components/secretary/tasks/TasksChargeProvider";
import { TASK_STATUS_LABELS } from "@/lib/secretary/tasks/labels";
import { CreateReminderButton } from "@/components/secretary/reminders/CreateReminderButton";
import { CreateMeetingButton } from "@/components/secretary/meetings/CreateMeetingButton";
import { prefillMeetingFromCommunication } from "@/lib/secretary/meetings/meeting-prefill";
import { CommunicationReminderBadge } from "@/components/secretary/reminders/CommunicationReminderBadge";
import { buildCommunicationLogReminderPayload } from "@/components/secretary/reminders/communication-builders";
import { useReminders } from "@/components/secretary/reminders/ReminderProvider";

type Props = {
  log: CommunicationLog;
  canMutate: boolean;
  onClose: () => void;
  onStatusChange: (log: CommunicationLog, status: CommunicationStatus) => void;
  onCopyMessage: (log: CommunicationLog) => void;
};

export function CommunicationDetailModal({
  log,
  canMutate,
  onClose,
  onStatusChange,
  onCopyMessage,
}: Props) {
  const { consents } = useReminders();
  const tasks = useSecretaryTasks();
  const linkedTask = log.linkedTaskId ? tasks.find((t) => t.id === log.linkedTaskId) : null;
  const reminderPayload = buildCommunicationLogReminderPayload(log, consents);

  return (
    <SecretaryEntityDetailModal
      open
      title="Λεπτομέρειες επικοινωνίας"
      subtitle={log.contactPerson}
      onClose={onClose}
      footer={
        canMutate ? (
          <div className="grid grid-cols-2 gap-2">
            <button
              type="button"
              onClick={() => onStatusChange({ ...log, status: "waiting_response" }, "waiting_response")}
              className="rounded-lg border border-border px-2 py-2 text-xs font-semibold"
            >
              Αναμονή απάντησης
            </button>
            <button
              type="button"
              onClick={() => onStatusChange({ ...log, status: "completed" }, "completed")}
              className="rounded-lg bg-emerald-600 px-2 py-2 text-xs font-bold text-white"
            >
              Ολοκλήρωση
            </button>
          </div>
        ) : null
      }
    >
      <div className="mb-3 flex flex-wrap gap-2">
        <CommunicationStatusBadge status={log.status} />
        <CommunicationPriorityBadge priority={log.priority} />
        {log.autoGenerated ? (
          <span className="rounded-md bg-violet-100 px-2 py-0.5 text-xs font-semibold text-violet-900">
            Αυτόματη
          </span>
        ) : null}
      </div>

      <dl className="space-y-2 text-sm">
        <Row label="Ημερομηνία" value={`${formatDateEl(log.communicationDate)}${log.communicationTime ? ` ${log.communicationTime}` : ""}`} />
        <Row label="Παιδί" value={log.childLabel ?? "—"} />
        <Row label="Γονέας" value={log.parentLabel ?? "—"} />
        <Row label="Επαφή" value={`${log.contactPerson} (${log.contactRole})`} />
        {log.contactPhone ? <Row label="Τηλέφωνο" value={log.contactPhone} /> : null}
        <Row label="Τύπος" value={log.communicationTypeLabel} />
        <Row label="Λόγος" value={log.reason} />
        <Row label="Περίληψη" value={log.summary} />
        {log.outcome ? <Row label="Αποτέλεσμα" value={log.outcome} /> : null}
        <Row label="Υπεύθυνος" value={log.responsiblePersonLabel ?? "—"} />
        {log.followUpDate ? <Row label="Follow-up" value={formatDateEl(log.followUpDate)} /> : null}
        {linkedTask ? (
          <Row
            label="Συνδ. εργασία"
            value={`${linkedTask.title} · ${TASK_STATUS_LABELS[linkedTask.status]}`}
          />
        ) : null}
      </dl>

      {canMutate ? (
        <div className="mt-4 flex flex-wrap gap-2 border-t border-border pt-3">
          {reminderPayload ? (
            <CreateReminderButton payload={reminderPayload} variant="primary" className="w-full sm:w-auto" />
          ) : null}
          <CreateMeetingButton
            prefill={prefillMeetingFromCommunication(log)}
            label="Νέα συνάντηση"
            size="sm"
          />
          <Link
            href={`/secretary/tasks?action=create&childId=${log.childId ?? ""}&child=${encodeURIComponent(log.childLabel ?? "")}`}
            className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-1.5 text-xs font-semibold"
          >
            <ListTodo className="h-3.5 w-3.5" />
            Follow-up εργασία
          </Link>
          {log.childId ? (
            <Link
              href={`/secretary/schedule?action=new&child=${encodeURIComponent(log.childLabel ?? "")}`}
              className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-1.5 text-xs font-semibold"
            >
              <Calendar className="h-3.5 w-3.5" />
              Ραντεβού
            </Link>
          ) : null}
          <button
            type="button"
            onClick={() => onCopyMessage(log)}
            className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-1.5 text-xs font-semibold"
          >
            <Copy className="h-3.5 w-3.5" />
            Αντιγραφή κειμένου
          </button>
          {log.linkedTaskId ? (
            <Link
              href={`/secretary/tasks?task=${log.linkedTaskId}`}
              className="text-xs font-semibold text-clinical-700 hover:underline"
            >
              Άνοιγμα εργασίας →
            </Link>
          ) : null}
        </div>
      ) : null}
    </SecretaryEntityDetailModal>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-4 border-b border-border/60 py-2">
      <dt className="text-ink-muted">{label}</dt>
      <dd className="max-w-[60%] text-right font-medium text-ink">{value}</dd>
    </div>
  );
}
