import type { CommunicationLog } from "@/lib/secretary/types";

/** Communication log entry created from reminder copy / send / phone log. */
export function isReminderCommunication(log: CommunicationLog): boolean {
  if (log.id.startsWith("comm-rem-")) return true;
  if (log.autoGenerated && log.createdByLabel?.includes("υπενθύμιση")) return true;
  if (log.reason?.startsWith("Υπενθύμιση:")) return true;
  return false;
}

export function reminderPageHref(log: CommunicationLog): string {
  if (log.childLabel) {
    return `/secretary/reminders?child=${encodeURIComponent(log.childLabel)}`;
  }
  return "/secretary/reminders";
}
