import type { CommunicationLog, ReportRequest } from "@/lib/secretary/types";
import type { RoleCode } from "@/lib/auth/roles";
import { todayAthensYmd } from "@/lib/schedule/athens-civil";
import { computeReportDashboardMetrics, isOpenReport } from "./calculations";

export type ReportBadgeTone = "green" | "yellow" | "red" | "dark_red";

export const REPORT_BADGE_CLASS: Record<ReportBadgeTone, string> = {
  green: "border-emerald-200 bg-emerald-50 text-emerald-900",
  yellow: "border-amber-300 bg-amber-100 text-amber-950",
  red: "border-red-300 bg-red-100 text-red-900",
  dark_red: "border-red-900 bg-red-950 text-red-50",
};

export type ReportsRoleView = "secretary" | "therapist" | "supervisor" | "clinical_director";

export function resolveReportsRoleView(
  roleCodes: RoleCode[],
  viewParam: string | null
): ReportsRoleView {
  if (viewParam === "therapist" || viewParam === "supervisor" || viewParam === "clinical_director") {
    return viewParam;
  }
  const isTherapistOnly =
    roleCodes.includes("THERAPIST") &&
    !roleCodes.some((r) => ["ORG_OWNER", "ORG_ADMIN", "RECEPTION", "SUPERVISOR"].includes(r));
  if (isTherapistOnly) return "therapist";
  if (roleCodes.includes("SUPERVISOR") && viewParam === null && !roleCodes.includes("RECEPTION")) {
    return "supervisor";
  }
  return "secretary";
}

export function reportsForTherapist(reports: ReportRequest[], therapistLabel: string | null): ReportRequest[] {
  if (!therapistLabel) {
    return reports.filter((r) =>
      ["assigned_therapist", "draft_in_progress", "corrections_requested"].includes(r.status)
    );
  }
  return reports.filter(
    (r) =>
      r.assignedTherapistLabels.includes(therapistLabel) ||
      r.assignedTherapistLabel === therapistLabel
  );
}

export function reportsForSupervisor(reports: ReportRequest[]): ReportRequest[] {
  return reports.filter((r) =>
    ["draft_completed", "supervisor_review", "corrections_requested"].includes(r.status)
  );
}

export function reportsForClinicalDirector(reports: ReportRequest[]): ReportRequest[] {
  return reports.filter(
    (r) =>
      r.status === "clinical_director_review" ||
      (r.clinicalDirectorApprovalRequired &&
        ["supervisor_review", "approved"].includes(r.status))
  );
}

export function reportsDueSoon(reports: ReportRequest[]): ReportRequest[] {
  return reports.filter((r) => isOpenReport(r) && r.isDueSoon && !r.isOverdue);
}

export function reportsReadyForDelivery(reports: ReportRequest[]): ReportRequest[] {
  return reports.filter((r) =>
    ["approved", "ready_for_delivery"].includes(r.status)
  );
}

export function reportBadgeForChild(
  reports: ReportRequest[],
  childId: string
): { label: string; tone: ReportBadgeTone; title: string; href: string } | null {
  const child = reports.filter((r) => r.childId === childId && isOpenReport(r));
  if (child.length === 0) return null;

  const overdue = child.filter((r) => r.isOverdue);
  const urgent = child.filter((r) => r.isUrgentOverdue);
  const dueSoon = child.filter((r) => r.isDueSoon && !r.isOverdue);
  const ready = child.filter((r) => ["approved", "ready_for_delivery"].includes(r.status));

  if (urgent.length > 0 || overdue.length > 0) {
    return {
      label: urgent.length > 0 ? "Επείγ. αναφορά" : "Εκπρόθ. αναφορά",
      tone: urgent.length > 0 ? "dark_red" : "red",
      title: `${overdue.length || urgent.length} αίτημα αναφοράς`,
      href: `/secretary/reports?child=${encodeURIComponent(child[0]!.childLabel)}&quick=overdue`,
    };
  }
  if (dueSoon.length > 0) {
    return {
      label: "Αναφορά σύντομα",
      tone: "yellow",
      title: `${dueSoon.length} αναφορές με προθεσμία εβδομάδας`,
      href: `/secretary/reports?child=${encodeURIComponent(child[0]!.childLabel)}&quick=due_week`,
    };
  }
  if (ready.length > 0) {
    return {
      label: "Έτοιμη αναφορά",
      tone: "green",
      title: `${ready.length} έτοιμες προς παράδοση`,
      href: `/secretary/reports?child=${encodeURIComponent(child[0]!.childLabel)}&quick=ready`,
    };
  }
  return {
    label: `${child.length} αναφορά`,
    tone: "yellow",
    title: "Ανοιχτά αιτήματα αναφορών",
    href: `/secretary/reports?child=${encodeURIComponent(child[0]!.childLabel)}`,
  };
}

export function isReportCommunication(log: CommunicationLog): boolean {
  return (
    log.reasonCode === "report_issue" ||
    !!log.linkedReportId ||
    (log.autoGenerated && (log.reason?.includes("αναφορ") ?? false))
  );
}

export function reportsDueReminderToday(
  reports: ReportRequest[],
  todayYmd: string = todayAthensYmd()
): ReportRequest[] {
  return reports.filter((r) => {
    if (!isOpenReport(r)) return false;
    if (r.isOverdue || r.isDueSoon) return true;
    if (["ready_for_delivery", "approved"].includes(r.status)) return true;
    if (r.dueDate === todayYmd) return true;
    return false;
  });
}

export function dashboardReportSummary(reports: ReportRequest[], todayYmd: string) {
  const open = reports.filter(isOpenReport);
  return {
    metrics: computeReportDashboardMetrics(reports, todayYmd),
    openCount: open.length,
    dueSoonCount: reportsDueSoon(open).length,
    overdueCount: open.filter((r) => r.isOverdue).length,
    readyCount: reportsReadyForDelivery(open).length,
    dueToday: reportsDueReminderToday(reports, todayYmd),
  };
}

/** Only final approved/delivered reports may appear in parent portal. */
export function reportsShareableWithParent(reports: ReportRequest[]): ReportRequest[] {
  return reports.filter(
    (r) =>
      !r.archived &&
      (r.status === "delivered" ||
        (["approved", "ready_for_delivery"].includes(r.status) && !!r.finalFileName))
  );
}

export function canShareReportWithParent(report: ReportRequest): boolean {
  return (
    report.status === "delivered" ||
    (["approved", "ready_for_delivery"].includes(report.status) && !!report.finalFileName)
  );
}
