import { addDaysAthensCalendar } from "@/lib/schedule/athens-civil";
import type { ReportRequest, TaskPriority } from "@/lib/secretary/types";
import { createTaskDraft, getAllTasks, upsertTask } from "@/lib/secretary/tasks/store";
import { taskTypeByCode } from "@/lib/secretary/tasks/catalog";
import { supervisorReviewPendingDays } from "./calculations";

type Milestone =
  | "created"
  | "assigned"
  | "draft_overdue"
  | "supervisor_pending"
  | "ready_delivery"
  | "delivered_close";

function findReportMilestoneTask(reportId: string, milestone: Milestone) {
  const today = new Date().toISOString().slice(0, 10);
  return getAllTasks(today).find(
    (t) =>
      t.linkedReportId === reportId &&
      t.notes.includes(`report:${milestone}`) &&
      !["completed", "cancelled"].includes(t.status)
  );
}

function createReportTask(
  report: ReportRequest,
  milestone: Milestone,
  todayYmd: string,
  taskTypeCode: string,
  title: string,
  dueDate: string,
  priority: TaskPriority,
  assignee: string
): void {
  if (findReportMilestoneTask(report.id, milestone)) return;
  if (report.archived || report.status === "cancelled") return;

  createTaskDraft(
    {
      taskTypeCode,
      taskTypeLabel: taskTypeByCode(taskTypeCode)?.labelEl ?? title,
      title,
      childId: report.childId,
      childLabel: report.childLabel,
      parentLabel: report.parentLabel,
      locationCode: report.locationCode,
      linkedReportId: report.id,
      assignedToLabel: assignee,
      priority,
      dueDate,
      notes: `report:${milestone} · ${report.reportTypeLabel}`,
      autoGenerated: true,
    },
    todayYmd
  );
}

export function syncAutoTasksFromReport(report: ReportRequest, todayYmd: string): void {
  if (report.archived) return;

  if (report.status === "requested") {
    createReportTask(
      report,
      "created",
      todayYmd,
      "report_monitoring",
      `Παρακολούθηση αναφοράς — ${report.childLabel}`,
      report.dueDate ?? addDaysAthensCalendar(todayYmd, 14),
      report.priority === "urgent" ? "urgent" : "normal",
      "Γραμματεία"
    );
  }

  if (report.status === "assigned_therapist" && report.assignedTherapistLabel) {
    createReportTask(
      report,
      "assigned",
      todayYmd,
      "report_request",
      `Σύνταξη αναφοράς — ${report.childLabel}`,
      report.dueDate ?? addDaysAthensCalendar(todayYmd, 10),
      report.isOverdue ? "urgent" : "high",
      report.assignedTherapistLabel
    );
  }

  if (report.isOverdue && ["draft_in_progress", "assigned_therapist", "corrections_requested"].includes(report.status)) {
    createReportTask(
      report,
      "draft_overdue",
      todayYmd,
      "report_followup",
      `Εκπρόθεσμη αναφορά — ${report.childLabel}`,
      todayYmd,
      "urgent",
      report.assignedTherapistLabel ?? "Γραμματεία"
    );
  }

  const supDays = supervisorReviewPendingDays(report, todayYmd);
  if (report.status === "supervisor_review" && supDays !== null && supDays > 3) {
    createReportTask(
      report,
      "supervisor_pending",
      todayYmd,
      "report_review",
      `Follow-up έλεγχος αναφοράς — ${report.childLabel}`,
      todayYmd,
      "high",
      report.assignedSupervisorLabel ?? "Επόπτης"
    );
  }

  if (report.status === "ready_for_delivery") {
    createReportTask(
      report,
      "ready_delivery",
      todayYmd,
      "report_delivery",
      `Παράδοση αναφοράς — ${report.childLabel}`,
      todayYmd,
      "high",
      "Γραμματεία"
    );
  }
}

export function closeReportTasks(reportId: string, todayYmd: string): void {
  const now = new Date().toISOString();
  const tasks = getAllTasks(todayYmd).filter(
    (t) => t.linkedReportId === reportId && !["completed", "cancelled"].includes(t.status)
  );
  for (const t of tasks) {
    upsertTask(
      {
        ...t,
        status: "completed",
        completionDate: todayYmd,
        updatedAt: now,
        notes: `${t.notes} · report:delivered_close`,
      },
      todayYmd
    );
  }
}
