import type { CommunicationLog, CommunicationReasonCode, CommunicationTypeCode } from "@/lib/secretary/types";
import type { ReportRequest } from "@/lib/secretary/types";
import type { ReminderChannel, ReminderEntityType, ReminderRecord } from "@/lib/secretary/reminders/types";
import { createCommunicationDraft } from "./store";
import { communicationLinksFromEntity } from "./entity-links";

function typeFromChannel(channel: ReminderChannel | null): CommunicationTypeCode {
  if (channel === "email") return "email";
  if (channel === "phone_call") return "parent_call";
  if (channel === "viber") return "viber";
  if (channel === "whatsapp") return "whatsapp";
  return "sms";
}

function reasonFromEntity(entityType: ReminderEntityType, templateLabel: string): CommunicationReasonCode {
  if (entityType === "payment") return "payment_issue";
  if (entityType === "appointment") return "schedule_issue";
  if (entityType === "diagnosis") return "diagnosis_issue";
  if (entityType === "report") return "report_issue";
  if (entityType === "task") return "prior_followup";
  if (entityType === "meeting") return "prior_followup";
  if (templateLabel.toLowerCase().includes("no-show") || templateLabel.includes("μη προσέλευση")) {
    return "schedule_issue";
  }
  return "parent_update";
}

export function autoLogFromReminder(
  reminder: ReminderRecord,
  channel: ReminderChannel | null,
  action: "copied" | "sent" | "phone_logged",
  todayYmd: string
): CommunicationLog {
  const typeCode = typeFromChannel(channel);
  const reasonCode = reasonFromEntity(reminder.entityType, reminder.templateLabel);
  const reasonLabel =
    reminder.entityType === "payment"
      ? `Πληρωμή: ${reminder.templateLabel}`
      : `Υπενθύμιση: ${reminder.templateLabel}`;

  return createCommunicationDraft(
    {
      id: `comm-rem-${reminder.id}-${action}`,
      childId: reminder.childId,
      childLabel: reminder.childLabel,
      parentLabel: reminder.recipientName,
      contactPerson: reminder.recipientName,
      contactRole: reminder.entityType === "payment" ? "parent" : "parent",
      contactPhone: reminder.recipientPhone,
      contactEmail: reminder.recipientEmail,
      communicationTypeCode: typeCode,
      communicationTypeLabel:
        channel === "email"
          ? "Email"
          : channel === "phone_call"
            ? "Τηλεφωνική επικοινωνία με γονέα"
            : channel === "viber"
              ? "Viber"
              : channel === "whatsapp"
                ? "WhatsApp"
                : "SMS",
      reasonCode,
      reason: reasonLabel,
      summary: reminder.messageBody.slice(0, 500),
      outcome: action === "sent" || action === "phone_logged" ? "Απεστάλη / καταγράφηκε" : "Αντιγράφηκε",
      status: "completed",
      nextActionRequired: false,
      priority: "normal",
      autoGenerated: true,
      createdByLabel: "Σύστημα (υπενθύμιση)",
      ...communicationLinksFromEntity(reminder.entityType, reminder.entityId),
    },
    todayYmd
  );
}

/** Log when a report request is received from parent / school / doctor. */
export function autoLogReportReceived(report: ReportRequest, todayYmd: string): CommunicationLog {
  const role =
    report.requestSource === "school"
      ? "school"
      : report.requestSource === "doctor"
        ? "doctor"
        : "parent";
  const typeCode =
    report.requestSource === "school"
      ? "school_call"
      : report.requestSource === "doctor"
        ? "doctor_call"
        : "parent_call";

  return createCommunicationDraft(
    {
      id: `comm-report-received-${report.id}`,
      childId: report.childId,
      childLabel: report.childLabel,
      contactPerson: report.requestedBy,
      contactRole: role,
      communicationTypeCode: typeCode,
      communicationTypeLabel:
        report.requestSource === "school"
          ? "Τηλεφωνική επικοινωνία με σχολείο"
          : report.requestSource === "doctor"
            ? "Τηλεφωνική επικοινωνία με γιατρό"
            : "Τηλεφωνική επικοινωνία με γονέα",
      reasonCode: "report_issue",
      reason: "Θέμα αναφοράς προόδου",
      summary: `Νέο αίτημα αναφοράς: ${report.reportTypeLabel} — ${report.purpose || report.requestedBy}`,
      outcome: "Καταχωρήθηκε αίτημα",
      status: "completed",
      nextActionRequired: false,
      priority: report.priority === "urgent" ? "urgent" : "normal",
      linkedReportId: report.id,
      autoGenerated: true,
      createdByLabel: report.createdByLabel,
    },
    todayYmd
  );
}

/** Notify parent that report is ready. */
export function autoLogReportParentNotified(report: ReportRequest, todayYmd: string): CommunicationLog {
  return createCommunicationDraft(
    {
      id: `comm-report-ready-${report.id}-${Date.now()}`,
      childId: report.childId,
      childLabel: report.childLabel,
      contactPerson: report.parentLabel ?? "Γονέας",
      contactRole: "parent",
      communicationTypeCode: "sms",
      communicationTypeLabel: "SMS",
      reasonCode: "report_issue",
      reason: "Θέμα αναφοράς προόδου",
      summary: `Ενημέρωση γονέα: η αναφορά ${report.reportTypeLabel} είναι έτοιμη προς παράδοση`,
      outcome: "Ο γονέας ενημερώθηκε",
      status: "completed",
      nextActionRequired: false,
      priority: "normal",
      linkedReportId: report.id,
      autoGenerated: true,
      createdByLabel: "Γραμματεία",
    },
    todayYmd
  );
}

/** Log when a progress report is marked delivered to the parent. */
export function autoLogReportDelivered(report: ReportRequest, todayYmd: string): CommunicationLog {
  return createCommunicationDraft(
    {
      id: `comm-report-delivered-${report.id}`,
      childId: report.childId,
      childLabel: report.childLabel,
      contactPerson: "Γονέας",
      contactRole: "parent",
      communicationTypeCode: "email",
      communicationTypeLabel: "Email",
      reasonCode: "report_issue",
      reason: "Θέμα αναφοράς προόδου",
      summary: `Παράδοση αναφοράς: ${report.reportTypeLabel}`,
      outcome: "Η αναφορά παραδόθηκε στον γονέα",
      status: "completed",
      nextActionRequired: false,
      priority: "normal",
      linkedReportId: report.id,
      autoGenerated: true,
      createdByLabel: "Γραμματεία",
    },
    todayYmd
  );
}
