import type { CommunicationLog } from "@/lib/secretary/types";
import { taskTypeByCode } from "@/lib/secretary/tasks/catalog";
import { createTaskDraft } from "@/lib/secretary/tasks/store";
import { commTypeToTaskCode } from "@/lib/secretary/tasks/auto-generate";

export function createFollowUpTaskFromCommunication(
  log: CommunicationLog,
  todayYmd: string
): string | null {
  if (!log.nextActionRequired && !log.nextAction && !log.followUpDate) return null;

  const typeCode = commTypeToTaskCode(log.communicationTypeCode);
  const task = createTaskDraft(
    {
      taskTypeCode: typeCode,
      taskTypeLabel: taskTypeByCode(typeCode)?.labelEl ?? log.communicationTypeLabel,
      title: log.nextAction?.trim() || `Follow-up: ${log.contactPerson}`,
      childId: log.childId,
      childLabel: log.childLabel,
      parentLabel: log.parentLabel,
      locationCode: log.locationCode,
      assignedToLabel: log.responsiblePersonLabel ?? "Γραμματεία",
      priority: log.priority,
      dueDate: log.followUpDate ?? todayYmd,
      dueTime: log.followUpTime,
      notes: `Από επικοινωνία ${log.id} · ${log.summary.slice(0, 100)}`,
      autoGenerated: true,
    },
    todayYmd
  );
  return task.id;
}
