import { getDemoOrganizationId } from "@/lib/config/demo";
import type { CommunicationLog, CommunicationReasonCode, CommunicationTypeCode } from "@/lib/secretary/types";
import { communicationReasonByCode, communicationTypeByCode } from "./catalog";
import { enrichCommunication } from "./calculations";

/** Maps legacy/partial records to full CommunicationLog shape. */
export function normalizeCommunicationLog(
  partial: Partial<CommunicationLog> & Pick<CommunicationLog, "id" | "contactPerson" | "summary">,
  todayYmd: string
): CommunicationLog {
  const occurred = partial.occurredAt ?? new Date().toISOString();
  const datePart = partial.communicationDate ?? occurred.slice(0, 10);
  const typeCode = (partial.communicationTypeCode ?? "other") as CommunicationTypeCode;
  const typeDef = communicationTypeByCode(typeCode);
  let reasonCode = partial.reasonCode ?? "other";
  if (!partial.reasonCode && partial.reason) {
    const match = COMMUNICATION_REASON_FROM_LEGACY(partial.reason);
    if (match) reasonCode = match;
  }
  const reasonDef = communicationReasonByCode(reasonCode);

  const raw: CommunicationLog = {
    id: partial.id,
    organizationId: partial.organizationId ?? getDemoOrganizationId(),
    locationCode: partial.locationCode ?? "nikaia",
    childId: partial.childId ?? null,
    childLabel: partial.childLabel ?? null,
    parentId: partial.parentId ?? null,
    parentLabel: partial.parentLabel ?? null,
    contactPerson: partial.contactPerson,
    contactRole: partial.contactRole ?? "other",
    contactPhone: partial.contactPhone ?? null,
    contactEmail: partial.contactEmail ?? null,
    communicationTypeCode: typeCode,
    communicationTypeLabel: partial.communicationTypeLabel ?? typeDef?.labelEl ?? typeCode,
    reasonCode: reasonCode as CommunicationReasonCode,
    reason: partial.reason ?? reasonDef?.labelEl ?? "—",
    summary: partial.summary,
    outcome: partial.outcome ?? null,
    nextActionRequired: partial.nextActionRequired ?? !!(partial.nextAction || partial.followUpDate),
    nextAction: partial.nextAction ?? null,
    followUpDate: partial.followUpDate ?? null,
    followUpTime: partial.followUpTime ?? null,
    priority: partial.priority ?? "normal",
    status: partial.status ?? (partial.nextAction || partial.followUpDate ? "needs_followup" : "completed"),
    responsiblePersonLabel: partial.responsiblePersonLabel ?? null,
    linkedTaskId: partial.linkedTaskId ?? null,
    linkedAppointmentId: partial.linkedAppointmentId ?? null,
    linkedPaymentId: partial.linkedPaymentId ?? null,
    linkedDiagnosisId: partial.linkedDiagnosisId ?? null,
    linkedReportId: partial.linkedReportId ?? null,
    linkedMeetingId: partial.linkedMeetingId ?? null,
    occurredAt: occurred,
    communicationDate: datePart,
    communicationTime: partial.communicationTime ?? null,
    createdByLabel: partial.createdByLabel ?? "Γραμματεία",
    createdAt: partial.createdAt ?? occurred,
    autoGenerated: partial.autoGenerated ?? false,
    alertLevel: partial.alertLevel ?? "green",
  };

  return enrichCommunication(raw, todayYmd);
}

function COMMUNICATION_REASON_FROM_LEGACY(reason: string): CommunicationReasonCode | null {
  if (reason.startsWith("Πληρωμή")) return "payment_issue";
  if (reason.includes("Συνεργασία")) return "school_request";
  if (reason.includes("υπενθύμιση") || reason.includes("Υπενθύμιση")) return "parent_update";
  return null;
}
