import type {
  ClientIntake,
  CommunicationLog,
  DiagnosisDocument,
  PaymentObligation,
  ReportRequest,
  SecretaryAppointment,
  SecretaryTask,
} from "@/lib/secretary/types";
import { syncAutoTasksFromDiagnosis } from "@/lib/secretary/diagnoses/sync-auto-tasks";
import { syncAutoTasksFromReport } from "@/lib/secretary/reports/sync-auto-tasks";
import { isOpenReport } from "@/lib/secretary/reports/calculations";
import { isOverdueCharge } from "@/lib/secretary/payments/payment-warnings";
import { taskTypeByCode } from "./catalog";
import { findTaskByLink, createTaskDraft, getAllTasks } from "./store";
import { addDaysAthensCalendar } from "@/lib/schedule/athens-civil";

function hasAutoTask(
  tasks: SecretaryTask[],
  predicate: (t: SecretaryTask) => boolean
): boolean {
  return tasks.some((t) => t.autoGenerated && predicate(t));
}

export function autoGenerateFromIntake(intake: ClientIntake, todayYmd: string): SecretaryTask | null {
  const tasks = getAllTasks(todayYmd);
  if (
    hasAutoTask(
      tasks,
      (t) =>
        t.taskTypeCode === "intake_followup" &&
        t.childLabel === `${intake.childLastName} ${intake.childFirstName}`.trim()
    )
  ) {
    return null;
  }
  return createTaskDraft(
    {
      taskTypeCode: "intake_followup",
      taskTypeLabel: taskTypeByCode("intake_followup")?.labelEl ?? "Follow-up intake",
      title: `Follow-up: ${intake.childFirstName} ${intake.childLastName}`,
      childLabel: `${intake.childLastName} ${intake.childFirstName}`,
      parentLabel: intake.parentPrimaryName || intake.parentNames,
      priority: intake.urgencyLevel === "urgent" ? "urgent" : "high",
      dueDate: addDaysAthensCalendar(todayYmd, 2),
      notes: `Αυτόματη εργασία από intake · ${intake.mainReason.slice(0, 80)}`,
      autoGenerated: true,
    },
    todayYmd
  );
}

export function autoGenerateFromOverduePayment(payment: PaymentObligation, todayYmd: string): SecretaryTask | null {
  if (payment.balance <= 0) return null;
  if (findTaskByLink("linkedPaymentId", payment.id)) return null;
  const tasks = getAllTasks(todayYmd);
  if (hasAutoTask(tasks, (t) => t.linkedPaymentId === payment.id)) return null;

  return createTaskDraft(
    {
      taskTypeCode: "payment_followup",
      taskTypeLabel: taskTypeByCode("payment_followup")?.labelEl ?? "Follow-up πληρωμής",
      title: `Follow-up πληρωμής — ${payment.childLabel}`,
      childId: payment.childId,
      childLabel: payment.childLabel,
      parentLabel: payment.parentLabel,
      locationCode: payment.locationCode,
      linkedPaymentId: payment.id,
      priority: payment.paymentStatus === "suspended_management" ? "urgent" : "high",
      dueDate: todayYmd,
      notes: `Υπόλοιπο ${payment.balance}€ · λήξη ${payment.dueDate}`,
      autoGenerated: true,
    },
    todayYmd
  );
}

export function autoGenerateFromDiagnosis(doc: DiagnosisDocument, todayYmd: string): SecretaryTask | null {
  if (doc.daysUntilExpiry > 60) return null;
  if (findTaskByLink("linkedDiagnosisId", doc.id)) return null;

  return createTaskDraft(
    {
      taskTypeCode: "diagnosis_followup",
      taskTypeLabel: taskTypeByCode("diagnosis_followup")?.labelEl ?? "Follow-up γνωμάτευσης",
      title: `Ανανέωση διάγνωσης — ${doc.childLabel}`,
      childId: doc.childId,
      childLabel: doc.childLabel,
      linkedDiagnosisId: doc.id,
      priority: doc.daysUntilExpiry <= 7 ? "urgent" : "high",
      dueDate: addDaysAthensCalendar(todayYmd, 7),
      notes: `Λήγει ${doc.expiryDate} (${doc.daysUntilExpiry} ημέρες)`,
      autoGenerated: true,
    },
    todayYmd
  );
}

export function autoGenerateFromNoShow(appt: SecretaryAppointment, todayYmd: string): SecretaryTask | null {
  if (appt.status !== "no_show") return null;
  if (findTaskByLink("linkedAppointmentId", appt.id)) return null;

  return createTaskDraft(
    {
      taskTypeCode: "no_show_followup",
      taskTypeLabel: taskTypeByCode("no_show_followup")?.labelEl ?? "Follow-up μη προσέλευσης",
      title: `Μη προσέλευση — ${appt.childLabel ?? "ραντεβού"}`,
      childId: appt.childId,
      childLabel: appt.childLabel,
      parentLabel: appt.parentLabel,
      locationCode: appt.locationCode,
      linkedAppointmentId: appt.id,
      priority: "high",
      dueDate: todayYmd,
      autoGenerated: true,
    },
    todayYmd
  );
}

export function autoGenerateFromReport(report: ReportRequest, todayYmd: string): SecretaryTask | null {
  if (report.status === "delivered" || report.status === "archived") return null;
  if (findTaskByLink("linkedReportId", report.id)) return null;

  return createTaskDraft(
    {
      taskTypeCode: "report_request",
      taskTypeLabel: taskTypeByCode("report_request")?.labelEl ?? "Αίτημα αναφοράς προόδου",
      title: `Παρακολούθηση αναφοράς — ${report.childLabel}`,
      childId: report.childId,
      childLabel: report.childLabel,
      linkedReportId: report.id,
      priority: report.dueDate && report.dueDate <= todayYmd ? "urgent" : "normal",
      dueDate: report.dueDate ?? addDaysAthensCalendar(todayYmd, 14),
      notes: `${report.reportTypeLabel} · ${report.status}`,
      autoGenerated: true,
    },
    todayYmd
  );
}

export function commTypeToTaskCode(code: CommunicationLog["communicationTypeCode"]): string {
  switch (code) {
    case "school_call":
      return "call_school";
    case "doctor_call":
      return "call_doctor";
    case "teacher_call":
      return "call_teacher";
    case "parallel_support_call":
      return "call_parallel";
    case "therapist_call":
      return "evaluation_request";
    case "supervisor_call":
      return "escalation_supervisor";
    case "partner_call":
      return "call_partner";
    case "parent_call":
      return "call_parent";
    default:
      return "send_message";
  }
}

export function autoGenerateFromCommunicationLog(
  log: CommunicationLog,
  todayYmd: string
): SecretaryTask | null {
  if (!log.nextActionRequired && !log.nextAction?.trim() && !log.followUpDate) return null;

  const tasks = getAllTasks(todayYmd);
  const actionKey = (log.nextAction ?? log.summary).slice(0, 60);
  if (
    hasAutoTask(
      tasks,
      (t) =>
        t.notes.includes(log.id) ||
        (t.childId === log.childId && t.title === actionKey && isActiveTaskStatus(t.status))
    )
  ) {
    return null;
  }

  const typeCode = commTypeToTaskCode(log.communicationTypeCode);
  return createTaskDraft(
    {
      taskTypeCode: typeCode,
      taskTypeLabel: taskTypeByCode(typeCode)?.labelEl ?? log.communicationTypeLabel,
      title: log.nextAction?.trim() || `Follow-up επικοινωνίας — ${log.contactPerson}`,
      childId: log.childId,
      childLabel: log.childLabel,
      priority: "normal",
      dueDate: log.followUpDate ?? addDaysAthensCalendar(todayYmd, 3),
      followUpDate: log.followUpDate,
      notes: `Από επικοινωνία (${log.id}) · ${log.summary.slice(0, 120)}`,
      autoGenerated: true,
    },
    todayYmd
  );
}

function isActiveTaskStatus(status: SecretaryTask["status"]): boolean {
  return !["completed", "cancelled"].includes(status);
}

/** Call after payment charge is saved — creates overdue follow-up when applicable. */
export function syncAutoTaskFromPayment(charge: PaymentObligation, todayYmd: string): void {
  if (charge.balance <= 0) return;
  if (
    isOverdueCharge(charge, todayYmd) ||
    charge.paymentStatus.startsWith("overdue") ||
    charge.paymentStatus === "suspended_management"
  ) {
    autoGenerateFromOverduePayment(charge, todayYmd);
  }
}

export function runAutoTaskGeneration(input: {
  payments: PaymentObligation[];
  diagnoses: DiagnosisDocument[];
  appointments: SecretaryAppointment[];
  reports?: ReportRequest[];
  intakes?: ClientIntake[];
  todayYmd: string;
}): number {
  let created = 0;
  for (const p of input.payments) {
    if (
      p.balance > 0 &&
      (p.paymentStatus.startsWith("overdue") ||
        p.paymentStatus === "overdue" ||
        p.paymentStatus === "suspended" ||
        p.paymentStatus === "suspended_management" ||
        isOverdueCharge(p, input.todayYmd))
    ) {
      if (autoGenerateFromOverduePayment(p, input.todayYmd)) created++;
    }
  }
  for (const d of input.diagnoses) {
    if (!d.archived && d.renewalRequired && !d.renewedAt) {
      const before = getAllTasks(input.todayYmd).length;
      syncAutoTasksFromDiagnosis(d, input.todayYmd);
      if (getAllTasks(input.todayYmd).length > before) created++;
    }
  }
  for (const a of input.appointments) {
    if (autoGenerateFromNoShow(a, input.todayYmd)) created++;
  }
  for (const r of input.reports ?? []) {
    if (!isOpenReport(r)) continue;
    const before = getAllTasks(input.todayYmd).length;
    syncAutoTasksFromReport(r, input.todayYmd);
    if (getAllTasks(input.todayYmd).length > before) created++;
  }
  return created;
}
