"use client";

import { getDemoOrganizationId } from "@/lib/config/demo";
import { SECRETARY_DEMO_TASKS } from "@/lib/demo/secretary-demo-data";
import type { SecretaryTask } from "@/lib/secretary/types";
import { enrichTask } from "./calculations";
import { taskTypeByCode } from "./catalog";

const STORAGE_KEY = "secretary-tasks-v1";

export const TASKS_UPDATED_EVENT = "secretary-tasks-updated";

function loadStored(): SecretaryTask[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    return JSON.parse(raw) as SecretaryTask[];
  } catch {
    return [];
  }
}

function persist(list: SecretaryTask[]) {
  if (typeof window === "undefined") return;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(list));
  window.dispatchEvent(new CustomEvent(TASKS_UPDATED_EVENT));
}

export function getAllTasks(todayYmd: string): SecretaryTask[] {
  const stored = loadStored();
  const demoIds = new Set(SECRETARY_DEMO_TASKS.map((t) => t.id));
  const byId = new Map<string, SecretaryTask>();
  for (const demo of SECRETARY_DEMO_TASKS) {
    const override = stored.find((s) => s.id === demo.id);
    byId.set(demo.id, enrichTask(override ?? demo, todayYmd));
  }
  for (const t of stored) {
    if (!demoIds.has(t.id)) byId.set(t.id, enrichTask(t, todayYmd));
  }
  const merged = [...byId.values()];
  return merged.sort((a, b) => {
    const da = a.dueDate ?? "9999-99-99";
    const db = b.dueDate ?? "9999-99-99";
    if (da !== db) return da.localeCompare(db);
    return Date.parse(b.updatedAt) - Date.parse(a.updatedAt);
  });
}

export function upsertTask(task: SecretaryTask, todayYmd: string): SecretaryTask {
  const enriched = enrichTask(task, todayYmd);
  const stored = loadStored();
  const demoIds = new Set(SECRETARY_DEMO_TASKS.map((t) => t.id));
  const idx = stored.findIndex((t) => t.id === enriched.id);
  if (idx >= 0) stored[idx] = enriched;
  else stored.unshift(enriched);
  persist(stored);
  return enriched;
}

export function findTaskByLink(
  field: "linkedPaymentId" | "linkedDiagnosisId" | "linkedReportId" | "linkedAppointmentId",
  id: string
): SecretaryTask | undefined {
  return loadStored().find((t) => t[field] === id) ?? getAllTasks(new Date().toISOString().slice(0, 10)).find((t) => t[field] === id);
}

export function createTaskDraft(
  partial: Partial<SecretaryTask> & Pick<SecretaryTask, "taskTypeCode" | "title">,
  todayYmd: string
): SecretaryTask {
  const type = partial.taskTypeCode;
  const now = new Date().toISOString();
  const task: SecretaryTask = {
    id: partial.id ?? `task-${Date.now()}`,
    organizationId: partial.organizationId ?? getDemoOrganizationId(),
    childId: partial.childId ?? null,
    childLabel: partial.childLabel ?? null,
    parentId: partial.parentId ?? null,
    parentLabel: partial.parentLabel ?? null,
    locationCode: partial.locationCode ?? "nikaia",
    staffMemberLabel: partial.staffMemberLabel ?? null,
    taskTypeCode: type,
    taskTypeLabel: partial.taskTypeLabel ?? taskTypeByCode(type)?.labelEl ?? type,
    title: partial.title,
    requestedByLabel: partial.requestedByLabel ?? "Γραμματεία",
    assignedToLabel: partial.assignedToLabel ?? "Γραμματεία",
    priority: partial.priority ?? "normal",
    status: partial.status ?? "open",
    dueDate: partial.dueDate ?? todayYmd,
    dueTime: partial.dueTime ?? null,
    followUpDate: partial.followUpDate ?? null,
    linkedAppointmentId: partial.linkedAppointmentId ?? null,
    linkedPaymentId: partial.linkedPaymentId ?? null,
    linkedDiagnosisId: partial.linkedDiagnosisId ?? null,
    linkedReportId: partial.linkedReportId ?? null,
    linkedMeetingId: partial.linkedMeetingId ?? null,
    completionDate: partial.completionDate ?? null,
    outcome: partial.outcome ?? null,
    notes: partial.notes ?? "",
    alertLevel: partial.alertLevel ?? "yellow",
    reminderDate: partial.reminderDate ?? null,
    reminderTime: partial.reminderTime ?? null,
    reminderStatus: partial.reminderStatus ?? "none",
    reminderMessage: partial.reminderMessage ?? null,
    autoGenerated: partial.autoGenerated ?? false,
    createdAt: partial.createdAt ?? now,
    updatedAt: now,
  };
  return upsertTask(task, todayYmd);
}
