import type { CommunicationLog, DiagnosisDocument } from "@/lib/secretary/types";
import { todayAthensYmd } from "@/lib/schedule/athens-civil";
import { worstDiagnosisForChild, diagnosisWarningSummary } from "./diagnosis-warnings";
import { computeDiagnosisDashboardMetrics } from "./calculations";

export type DiagnosisBadgeTone = "green" | "yellow" | "red" | "dark_red";

export const DIAGNOSIS_BADGE_CLASS: Record<DiagnosisBadgeTone, string> = {
  green: "border-emerald-200 bg-emerald-50 text-emerald-900",
  yellow: "border-amber-300 bg-amber-100 text-amber-950",
  red: "border-red-300 bg-red-100 text-red-900",
  dark_red: "border-red-900 bg-red-950 text-red-50",
};

export function documentsForChild(docs: DiagnosisDocument[], childId: string): DiagnosisDocument[] {
  return docs.filter((d) => d.childId === childId && !d.archived);
}

export function expiredDocuments(docs: DiagnosisDocument[]): DiagnosisDocument[] {
  return docs.filter((d) => !d.archived && d.status === "expired");
}

export function expiringDocuments(docs: DiagnosisDocument[]): DiagnosisDocument[] {
  return docs.filter(
    (d) =>
      !d.archived &&
      ["expiring_60", "expiring_30", "expiring_7", "renewal_in_progress"].includes(d.status)
  );
}

export function diagnosisBadgeForChild(
  docs: DiagnosisDocument[],
  childId: string
): { label: string; tone: DiagnosisBadgeTone; title: string; href: string } | null {
  const doc = worstDiagnosisForChild(docs, childId);
  if (!doc) return null;
  const summary = diagnosisWarningSummary(doc);
  if (summary.level === "none") return null;

  const tone: DiagnosisBadgeTone =
    summary.level === "red"
      ? doc.daysUntilExpiry < 0 && !doc.renewalProcessStarted
        ? "dark_red"
        : "red"
      : "yellow";

  return {
    label: summary.level === "red" ? "Ληγμένη γνωμάτευση" : "Γνωμάτευση λήγει",
    tone,
    title: summary.detail,
    href: `/secretary/diagnoses?child=${encodeURIComponent(doc.childLabel)}`,
  };
}

export function isDiagnosisCommunication(log: CommunicationLog): boolean {
  return (
    log.reasonCode === "diagnosis_issue" ||
    !!log.linkedDiagnosisId ||
    log.autoGenerated && (log.reason?.toLowerCase().includes("διάγνωση") ?? false)
  );
}

export function diagnosisDocumentsDueReminderToday(
  docs: DiagnosisDocument[],
  todayYmd: string = todayAthensYmd()
): DiagnosisDocument[] {
  return docs.filter((d) => {
    if (d.archived || !d.renewalRequired || d.renewedAt) return false;
    if (d.renewalFollowUpDate === todayYmd) return true;
    if (d.status === "expiring_7" || d.status === "expired") return true;
    return false;
  });
}

export function dashboardDiagnosisSummary(docs: DiagnosisDocument[], todayYmd: string) {
  const m = computeDiagnosisDashboardMetrics(docs, todayYmd);
  return {
    metrics: m,
    dueToday: diagnosisDocumentsDueReminderToday(docs, todayYmd),
  };
}
