import { addDaysAthensCalendar } from "@/lib/schedule/athens-civil";
import type { DiagnosisDocument } from "@/lib/secretary/types";
import { createTaskDraft } from "@/lib/secretary/tasks/store";
import { taskTypeByCode } from "@/lib/secretary/tasks/catalog";
import { upsertDiagnosis } from "./store";
import { enrichDiagnosis } from "./calculations";

export function startRenewalProcess(
  doc: DiagnosisDocument,
  todayYmd: string,
  options?: { responsiblePersonLabel?: string; followUpDate?: string }
): { doc: DiagnosisDocument; taskId: string } {
  const followUp =
    options?.followUpDate ?? doc.renewalFollowUpDate ?? addDaysAthensCalendar(todayYmd, 14);
  const responsible = options?.responsiblePersonLabel ?? doc.responsiblePersonLabel ?? "Γραμματεία";

  const updated = upsertDiagnosis(
    enrichDiagnosis(
      {
        ...doc,
        renewalProcessStarted: true,
        renewalFollowUpDate: followUp,
        responsiblePersonLabel: responsible,
      },
      todayYmd
    ),
    todayYmd
  );

  const task = createTaskDraft(
    {
      taskTypeCode: "diagnosis_followup",
      taskTypeLabel: taskTypeByCode("diagnosis_followup")?.labelEl ?? "Follow-up γνωμάτευσης",
      title: `Ανανέωση γνωμάτευσης — ${doc.childLabel}`,
      childId: doc.childId,
      childLabel: doc.childLabel,
      parentLabel: doc.parentLabel,
      locationCode: doc.locationCode,
      linkedDiagnosisId: doc.id,
      assignedToLabel: responsible,
      priority: doc.daysUntilExpiry < 0 ? "urgent" : "high",
      dueDate: followUp,
      notes: `milestone:renewal · ${doc.documentType} · λήξη ${doc.expiryDate}`,
      autoGenerated: true,
    },
    todayYmd
  );

  return { doc: updated, taskId: task.id };
}

export function markDiagnosisRenewed(doc: DiagnosisDocument, todayYmd: string): DiagnosisDocument {
  return upsertDiagnosis(
    enrichDiagnosis(
      {
        ...doc,
        renewedAt: todayYmd,
        renewalProcessStarted: false,
        renewalRequired: false,
      },
      todayYmd
    ),
    todayYmd
  );
}

export function archiveDiagnosis(doc: DiagnosisDocument, todayYmd: string): DiagnosisDocument {
  const now = new Date().toISOString();
  return upsertDiagnosis(
    enrichDiagnosis(
      {
        ...doc,
        archived: true,
        updatedAt: now,
        updatedByLabel: doc.updatedByLabel ?? "Γραμματεία",
      },
      todayYmd
    ),
    todayYmd
  );
}
