import type { DiagnosisDocument, TaskPriority } from "@/lib/secretary/types";
import { addDaysAthensCalendar } from "@/lib/schedule/athens-civil";
import { getAllTasks, createTaskDraft } from "@/lib/secretary/tasks/store";
import { taskTypeByCode } from "@/lib/secretary/tasks/catalog";

type Milestone = "60" | "30" | "7" | "expired";

function findDiagnosisMilestoneTask(docId: string, milestone: Milestone) {
  const tasks = getAllTasks(new Date().toISOString().slice(0, 10));
  return tasks.find(
    (t) =>
      t.linkedDiagnosisId === docId &&
      t.notes.includes(`milestone:${milestone}`) &&
      !["completed", "cancelled"].includes(t.status)
  );
}

function createMilestoneTask(
  doc: DiagnosisDocument,
  milestone: Milestone,
  todayYmd: string,
  dueDate: string,
  priority: TaskPriority
): void {
  if (findDiagnosisMilestoneTask(doc.id, milestone)) return;
  if (doc.archived || !doc.renewalRequired || doc.renewedAt) return;

  createTaskDraft(
    {
      taskTypeCode: "diagnosis_followup",
      taskTypeLabel: taskTypeByCode("diagnosis_followup")?.labelEl ?? "Follow-up γνωμάτευσης",
      title: `Γνωμάτευση (${milestone === "expired" ? "ληγμένη" : `${milestone}ημ.`}) — ${doc.childLabel}`,
      childId: doc.childId,
      childLabel: doc.childLabel,
      parentLabel: doc.parentLabel,
      locationCode: doc.locationCode,
      linkedDiagnosisId: doc.id,
      assignedToLabel: doc.responsiblePersonLabel ?? "Γραμματεία",
      priority,
      dueDate,
      notes: `milestone:${milestone} · ${doc.documentType} · λήξη ${doc.expiryDate}`,
      autoGenerated: true,
    },
    todayYmd
  );
}

/** Auto-create follow-up tasks at 60/30/7 days and after expiry. */
export function syncAutoTasksFromDiagnosis(doc: DiagnosisDocument, todayYmd: string): void {
  if (doc.archived || !doc.renewalRequired || doc.renewedAt || doc.renewalProcessStarted) {
    return;
  }

  const days = doc.daysUntilExpiry;

  if (days <= 60 && days > 30) {
    createMilestoneTask(doc, "60", todayYmd, addDaysAthensCalendar(doc.expiryDate, -30), "normal");
  }
  if (days <= 30 && days > 7) {
    createMilestoneTask(doc, "30", todayYmd, addDaysAthensCalendar(doc.expiryDate, -7), "high");
  }
  if (days <= 7 && days >= 0) {
    createMilestoneTask(doc, "7", todayYmd, doc.expiryDate, "urgent");
  }
  if (days < 0) {
    createMilestoneTask(doc, "expired", todayYmd, todayYmd, "urgent");
  }
}
