"use client";

import { useState } from "react";
import Link from "next/link";
import { Calendar, Copy, MessageCircle, Pencil } from "lucide-react";
import { NewCommunicationLink } from "@/components/secretary/communications/NewCommunicationLink";
import type { SecretaryTask, TaskStatus } from "@/lib/secretary/types";
import { SecretaryEntityDetailModal } from "@/components/secretary/SecretaryEntityDetailModal";
import { CreateReminderButton } from "@/components/secretary/reminders/CreateReminderButton";
import { CreateMeetingButton } from "@/components/secretary/meetings/CreateMeetingButton";
import { prefillMeetingFromTask } from "@/lib/secretary/meetings/meeting-prefill";
import { buildTaskCommunicationPayload } from "@/components/secretary/reminders/communication-builders";
import type { CommunicationConsent } from "@/lib/secretary/reminders/types";
import { linkedItemLabel } from "@/lib/secretary/tasks/calculations";
import { taskTypeRequiresCommLog } from "@/lib/secretary/tasks/catalog";
import { formatDateEl } from "@/lib/ui/child-labels";
import { TaskStatusBadge } from "./TaskStatusBadge";
import { TaskPriorityBadge } from "./TaskPriorityBadge";
import { todayAthensYmd } from "@/lib/schedule/athens-civil";

type Props = {
  task: SecretaryTask;
  consents: CommunicationConsent[];
  canMutate: boolean;
  onClose: () => void;
  onSave: (task: SecretaryTask) => void;
  onStatusChange: (task: SecretaryTask, status: TaskStatus) => void;
  onCompleteWithComm: (task: SecretaryTask) => void;
  onFollowUp: (task: SecretaryTask) => void;
  onCopyReminder: (task: SecretaryTask) => void;
  onMarkReminderSent: (task: SecretaryTask) => void;
};

export function TaskDetailModal({
  task: initial,
  consents,
  canMutate,
  onClose,
  onSave,
  onStatusChange,
  onCompleteWithComm,
  onFollowUp,
  onCopyReminder,
  onMarkReminderSent,
}: Props) {
  const [editing, setEditing] = useState(false);
  const [task, setTask] = useState(initial);
  const today = todayAthensYmd();
  const payload = task.childId ? buildTaskCommunicationPayload(task, consents) : null;
  const needsComm = taskTypeRequiresCommLog(task.taskTypeCode);

  const saveEdits = () => {
    onSave({ ...task, updatedAt: new Date().toISOString() });
    setEditing(false);
  };

  const complete = () => {
    if (needsComm && task.status !== "completed") {
      onCompleteWithComm(task);
      return;
    }
    onStatusChange(
      {
        ...task,
        status: "completed",
        completionDate: today,
        updatedAt: new Date().toISOString(),
      },
      "completed"
    );
  };

  return (
    <SecretaryEntityDetailModal
      open
      title="Λεπτομέρειες εργασίας"
      subtitle={task.title}
      onClose={onClose}
      footer={
        <div className="flex flex-col gap-2">
          {payload ? <CreateReminderButton payload={payload} className="w-full" variant="primary" /> : null}
          <CreateMeetingButton prefill={prefillMeetingFromTask(task)} className="w-full" label="Νέα συνάντηση" />
          {canMutate ? (
            <div className="grid grid-cols-2 gap-2">
              <button
                type="button"
                onClick={() => onStatusChange({ ...task, status: "in_progress" }, "in_progress")}
                className="rounded-lg border border-border px-2 py-2 text-xs font-semibold hover:bg-surface-muted"
              >
                Σε εξέλιξη
              </button>
              <button
                type="button"
                onClick={() => onStatusChange({ ...task, status: "waiting_response" }, "waiting_response")}
                className="rounded-lg border border-border px-2 py-2 text-xs font-semibold hover:bg-surface-muted"
              >
                Αναμονή απάντησης
              </button>
              <button
                type="button"
                onClick={complete}
                className="col-span-2 rounded-lg bg-emerald-600 px-2 py-2 text-xs font-bold text-white hover:bg-emerald-700"
              >
                Ολοκλήρωση
              </button>
            </div>
          ) : null}
        </div>
      }
    >
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <TaskPriorityBadge priority={task.priority} />
        <TaskStatusBadge status={task.status} />
        {task.autoGenerated ? (
          <span className="rounded-md bg-violet-100 px-2 py-0.5 text-xs font-semibold text-violet-900">Αυτόματη</span>
        ) : null}
        {canMutate ? (
          <button
            type="button"
            onClick={() => (editing ? saveEdits() : setEditing(true))}
            className="ml-auto inline-flex items-center gap-1 text-xs font-semibold text-clinical-700"
          >
            <Pencil className="h-3.5 w-3.5" />
            {editing ? "Αποθήκευση" : "Επεξεργασία"}
          </button>
        ) : null}
      </div>

      <dl className="space-y-2 text-sm">
        <Row label="Τύπος" value={task.taskTypeLabel} />
        <Row label="Παιδί" value={task.childLabel ?? "—"} />
        <Row label="Γονέας" value={task.parentLabel ?? "—"} />
        <Row label="Υπεύθυνος" value={task.assignedToLabel ?? "—"} />
        <Row label="Ζητήθηκε από" value={task.requestedByLabel ?? "—"} />
        <Row label="Προθεσμία" value={task.dueDate ? `${formatDateEl(task.dueDate)}${task.dueTime ? ` ${task.dueTime}` : ""}` : "—"} />
        <Row label="Σύνδεση" value={linkedItemLabel(task)} />
        {task.followUpDate ? <Row label="Follow-up" value={formatDateEl(task.followUpDate)} /> : null}
        {task.outcome ? <Row label="Αποτέλεσμα" value={task.outcome} /> : null}
        {editing ? (
          <label className="block pt-2">
            <span className="text-ink-muted">Σημειώσεις</span>
            <textarea
              value={task.notes}
              onChange={(e) => setTask({ ...task, notes: e.target.value })}
              rows={3}
              className="mt-1 w-full rounded-lg border border-border px-3 py-2"
            />
          </label>
        ) : task.notes ? (
          <Row label="Σημειώσεις" value={task.notes} />
        ) : null}
      </dl>

      {canMutate ? (
        <div className="mt-4 flex flex-wrap gap-2 border-t border-border pt-3">
          <NewCommunicationLink
            size="sm"
            params={{
              task: task.id,
              childId: task.childId,
              childLabel: task.childLabel,
            }}
          />
          <button
            type="button"
            onClick={() => onFollowUp(task)}
            className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-1.5 text-xs font-semibold hover:bg-surface-muted"
          >
            <Calendar className="h-3.5 w-3.5" />
            Follow-up
          </button>
          {task.linkedAppointmentId ? (
            <Link
              href={`/secretary/schedule?appointment=${task.linkedAppointmentId}`}
              className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-1.5 text-xs font-semibold hover:bg-surface-muted"
            >
              Ραντεβού
            </Link>
          ) : (
            <Link
              href={`/secretary/schedule?action=new&child=${encodeURIComponent(task.childLabel ?? "")}`}
              className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-1.5 text-xs font-semibold hover:bg-surface-muted"
            >
              Νέο ραντεβού
            </Link>
          )}
          <button
            type="button"
            onClick={() => onCopyReminder(task)}
            className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-1.5 text-xs font-semibold hover:bg-surface-muted"
          >
            <Copy className="h-3.5 w-3.5" />
            Αντιγραφή υπενθύμισης
          </button>
          <button
            type="button"
            onClick={() => onMarkReminderSent(task)}
            className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-1.5 text-xs font-semibold hover:bg-surface-muted"
          >
            <MessageCircle className="h-3.5 w-3.5" />
            Υπενθύμιση απεστάλη
          </button>
        </div>
      ) : null}
    </SecretaryEntityDetailModal>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-4 border-b border-border/60 py-2">
      <dt className="shrink-0 text-ink-muted">{label}</dt>
      <dd className="text-right font-medium text-ink">{value}</dd>
    </div>
  );
}
