/**
 * Static demo data for Secretary Control Center.
 */

import type {
  CaseProgram,
  ClientIntake,
  CommunicationLog,
  DiagnosisDocument,
  InternalMeeting,
  PaymentObligation,
  ReportRequest,
  SecretaryAppointment,
  SecretaryDashboardData,
  SecretaryTask,
} from "@/lib/secretary/types";
import { addDaysAthensCalendar, todayAthensYmd } from "@/lib/schedule/athens-civil";
import {
  appointmentTypeByCode,
  parentLabelForChild,
} from "@/lib/secretary/schedule-catalog";
import { detectAppointmentConflicts } from "@/lib/secretary/conflicts";
import { enrichReport } from "@/lib/secretary/reports/calculations";
import { normalizeReportRequest } from "@/lib/secretary/reports/normalize";
import { addMinutesToIso, appointmentYmdAthens, athensCivilToUtcIso } from "@/lib/secretary/schedule-utils";
import type { AppointmentReminderStatus } from "@/lib/secretary/types";

const ORG = "10000000-0000-4000-8000-000000000001";
const today = todayAthensYmd();

/** Civil day when demo appointment slots were built (shifted at load for schedule view). */
export const SECRETARY_DEMO_SCHEDULE_ANCHOR_YMD = today;

function athensSlot(ymd: string, hour: number, minute: number, durationMin: number): {
  startsAt: string;
  endsAt: string;
} {
  const startsAt = athensCivilToUtcIso(ymd, hour, minute);
  const endsAt = addMinutesToIso(startsAt, durationMin);
  return { startsAt, endsAt };
}

export const SECRETARY_DEMO_APPOINTMENT_TYPES = [
  { code: "parent_info", nameEl: "Συνάντηση ενημέρωσης γονέων", defaultDurationMin: 45, isClinicalSession: false },
  { code: "evaluation", nameEl: "Αξιολόγηση", defaultDurationMin: 60, isClinicalSession: true },
  { code: "therapy_session", nameEl: "Θεραπευτική συνεδρία", defaultDurationMin: 45, isClinicalSession: true },
] as const;

export const SECRETARY_DEMO_APPOINTMENTS: SecretaryAppointment[] = [
  {
    id: "sa-demo-1",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000101",
    childLabel: "Παπαδόπουλος Ν.",
    parentId: null,
    appointmentTypeCode: "evaluation",
    appointmentTypeLabel: "Αξιολόγηση",
    locationCode: "nikaia",
    ...athensSlot(today, 15, 0, 60),
    status: "confirmed",
    priority: "high",
    roomId: "30000000-0000-4000-8000-000000000001",
    roomLabel: "Αίθ. 1",
    staffIds: ["staff-demo-1"],
    staffLabels: ["Δρ. Ανδρέου (ΚΔ)"],
    notes: "",
    reminderAt: null,
    sessionId: null,
  },
  {
    id: "sa-demo-2",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000102",
    childLabel: "Οικονομίδου Ε.",
    parentId: null,
    appointmentTypeCode: "parent_info",
    appointmentTypeLabel: "Ενημερωτικό ραντεβού",
    locationCode: "evosmos",
    ...athensSlot(today, 17, 0, 45),
    status: "scheduled",
    priority: "normal",
    roomId: "30000000-0000-4000-8000-000000000002",
    roomLabel: "Αίθ. 2",
    staffIds: ["staff-demo-2"],
    staffLabels: ["Γεωργίου Ε. (Ψυχ.)"],
    notes: "Νέο αίτημα",
    reminderAt: null,
    sessionId: null,
  },
  {
    id: "sa-demo-3",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000103",
    childLabel: "Τσίτσος Μ.",
    parentId: null,
    appointmentTypeCode: "therapy_session",
    appointmentTypeLabel: "Θεραπευτική συνεδρία",
    locationCode: "nikaia",
    ...athensSlot(today, 15, 30, 45),
    status: "confirmed",
    priority: "normal",
    roomId: "30000000-0000-4000-8000-000000000001",
    roomLabel: "Αίθ. 1",
    staffIds: ["staff-demo-3"],
    staffLabels: ["Βασιλείου Ν. (Λογ.)"],
    notes: "",
    reminderAt: null,
    sessionId: null,
  },
  {
    id: "sa-demo-4",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000104",
    childLabel: "Φωτίου Κ.",
    parentId: null,
    appointmentTypeCode: "diagnosis_renewal",
    appointmentTypeLabel: "Ανανέωση γνωμάτευσης",
    locationCode: "nikaia",
    ...athensSlot(today, 18, 30, 30),
    status: "scheduled",
    priority: "urgent",
    roomId: "30000000-0000-4000-8000-000000000003",
    roomLabel: "Αίθ. 3",
    staffIds: ["staff-demo-1"],
    staffLabels: ["Δρ. Ανδρέου (ΚΔ)"],
    notes: "Ληγμένο έγγραφο",
    reminderAt: null,
    sessionId: null,
  },
  {
    id: "sa-demo-5",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000102",
    childLabel: "Οικονομίδου Ε.",
    parentId: null,
    appointmentTypeCode: "therapy_session",
    appointmentTypeLabel: "Θεραπευτική συνεδρία",
    locationCode: "evosmos",
    ...athensSlot(addDaysAthensCalendar(today, 1), 15, 30, 45),
    status: "scheduled",
    priority: "normal",
    roomId: "30000000-0000-4000-8000-000000000002",
    roomLabel: "Αίθ. 2",
    staffIds: ["staff-demo-2"],
    staffLabels: ["Γεωργίου Ε. (Ψυχ.)"],
    notes: "",
    reminderAt: null,
    sessionId: null,
  },
  {
    id: "sa-demo-6",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000101",
    childLabel: "Παπαδόπουλος Ν.",
    parentId: null,
    appointmentTypeCode: "therapy_session",
    appointmentTypeLabel: "Θεραπευτική συνεδρία",
    locationCode: "nikaia",
    ...athensSlot(addDaysAthensCalendar(today, 2), 14, 0, 45),
    status: "scheduled",
    priority: "normal",
    roomId: "30000000-0000-4000-8000-000000000001",
    roomLabel: "Αίθ. 1",
    staffIds: ["staff-demo-3"],
    staffLabels: ["Βασιλείου Ν. (Λογ.)"],
    notes: "",
    reminderAt: null,
    sessionId: null,
  },
  {
    id: "sa-demo-7",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000104",
    childLabel: "Φωτίου Κ.",
    parentId: null,
    appointmentTypeCode: "history_taking",
    appointmentTypeLabel: "Λήψη ιστορικού",
    locationCode: "nikaia",
    ...athensSlot(today, 16, 0, 60),
    status: "scheduled",
    priority: "normal",
    roomId: "30000000-0000-4000-8000-000000000001",
    roomLabel: "Αίθ. 1",
    staffIds: [],
    staffLabels: [],
    notes: "Χωρίς θεραπευτή — δοκιμαστική προειδοποίηση",
    reminderAt: null,
    sessionId: null,
  },
  {
    id: "sa-demo-8",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000101",
    childLabel: "Παπαδόπουλος Ν.",
    parentId: null,
    appointmentTypeCode: "supervision",
    appointmentTypeLabel: "Εποπτεία",
    locationCode: "evosmos",
    ...athensSlot(addDaysAthensCalendar(today, 5), 14, 0, 60),
    status: "confirmed",
    priority: "normal",
    roomId: "30000000-0000-4000-8000-000000000002",
    roomLabel: "Αίθ. 2",
    staffIds: ["staff-demo-1"],
    staffLabels: ["Δρ. Ανδρέου (ΚΔ)"],
    notes: "",
    reminderAt: null,
    sessionId: null,
  },
].map((a) => enrichDemoAppointment(a as Omit<SecretaryAppointment, "parentLabel" | "reminderStatus">));

function enrichDemoAppointment(
  a: SecretaryAppointment | (Omit<SecretaryAppointment, "parentLabel" | "reminderStatus"> & {
    parentLabel?: string | null;
    reminderStatus?: AppointmentReminderStatus;
  })
): SecretaryAppointment {
  const type = appointmentTypeByCode(a.appointmentTypeCode);
  return {
    ...a,
    parentLabel: a.parentLabel ?? parentLabelForChild(a.childId),
    reminderStatus: a.reminderStatus ?? (a.reminderAt ? "scheduled" : "pending"),
    appointmentTypeLabel: type?.nameEl ?? a.appointmentTypeLabel,
  };
}

export const SECRETARY_DEMO_PAYMENTS: PaymentObligation[] = [
  {
    id: "pay-demo-1",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000101",
    childLabel: "Παπαδόπουλος Ν.",
    parentId: null,
    parentLabel: "Παπαδόπουλου Μ.",
    locationCode: "nikaia",
    obligationMonth: `${today.slice(0, 7)}-01`,
    programLabel: "Λογοθεραπεία — μηνιαίο πακέτο",
    expectedAmount: 320,
    paidAmount: 0,
    balance: 320,
    dueDate: addDaysAthensCalendar(today, 5),
    paymentDate: null,
    paymentMethod: null,
    paymentStatus: "due_soon",
    alertLevel: "yellow",
    receiptStatus: "pending",
    notes: "",
    escalatedToManagement: false,
    expectedAmountLocked: true,
    lastReminderAt: null,
  },
  {
    id: "pay-demo-2",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000103",
    childLabel: "Τσίτσος Μ.",
    parentId: null,
    parentLabel: "Τσίτσου Α.",
    locationCode: "evosmos",
    obligationMonth: addDaysAthensCalendar(today, -35).slice(0, 7) + "-01",
    programLabel: "Εργοθεραπεία",
    expectedAmount: 280,
    paidAmount: 100,
    balance: 180,
    dueDate: addDaysAthensCalendar(today, -18),
    paymentDate: addDaysAthensCalendar(today, -40),
    paymentMethod: "bank_transfer",
    paymentStatus: "overdue_1_30",
    alertLevel: "red",
    receiptStatus: "issued",
    notes: "Υπενθύμιση 12/05",
    escalatedToManagement: false,
    expectedAmountLocked: true,
    lastReminderAt: `${today}T09:00:00.000Z`,
  },
  {
    id: "pay-demo-3",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000104",
    childLabel: "Φωτίου Κ.",
    parentId: null,
    parentLabel: "Φωτίου Ανδρέας",
    locationCode: "nikaia",
    obligationMonth: addDaysAthensCalendar(today, -70).slice(0, 7) + "-01",
    programLabel: "Ψυχολογική υποστήριξη",
    expectedAmount: 360,
    paidAmount: 60,
    balance: 300,
    dueDate: addDaysAthensCalendar(today, -65),
    paymentDate: addDaysAthensCalendar(today, -70),
    paymentMethod: "cash",
    paymentStatus: "suspended_management",
    alertLevel: "red",
    receiptStatus: "needs_review",
    notes: "Επαναλαμβανόμενή καθυστέρηση",
    escalatedToManagement: true,
    expectedAmountLocked: true,
    lastReminderAt: addDaysAthensCalendar(today, -3) + "T11:00:00.000Z",
  },
  {
    id: "pay-demo-4",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000102",
    childLabel: "Οικονομίδου Ε.",
    parentId: null,
    parentLabel: "Οικονομίδης Γ.",
    locationCode: "evosmos",
    obligationMonth: `${today.slice(0, 7)}-01`,
    programLabel: "Λογοθεραπεία",
    expectedAmount: 300,
    paidAmount: 300,
    balance: 0,
    dueDate: addDaysAthensCalendar(today, -2),
    paymentDate: today,
    paymentMethod: "pos",
    paymentStatus: "paid",
    alertLevel: "green",
    receiptStatus: "issued",
    notes: "",
    escalatedToManagement: false,
    expectedAmountLocked: true,
    lastReminderAt: null,
  },
];

const taskBase = (partial: SecretaryTask): SecretaryTask => partial;

export const SECRETARY_DEMO_TASKS: SecretaryTask[] = [
  taskBase({
    id: "task-demo-1",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000102",
    childLabel: "Οικονομίδου Ε.",
    parentId: null,
    parentLabel: "Οικονομίδου Μαρία",
    locationCode: "nikaia",
    staffMemberLabel: null,
    taskTypeCode: "call_school",
    taskTypeLabel: "Τηλεφωνική επικοινωνία με σχολείο",
    title: "Ζήτηση παράλληλης στήριξης",
    requestedByLabel: "Γονέας",
    assignedToLabel: "Γραμματεία",
    priority: "high",
    status: "open",
    dueDate: addDaysAthensCalendar(today, 0),
    dueTime: "14:00",
    followUpDate: addDaysAthensCalendar(today, 7),
    linkedAppointmentId: null,
    linkedPaymentId: null,
    linkedDiagnosisId: null,
    linkedReportId: null,
    linkedMeetingId: null,
    completionDate: null,
    outcome: null,
    notes: "Αναμονή απάντησης από διευθύντρια.",
    alertLevel: "yellow",
    reminderDate: today,
    reminderTime: "13:30",
    reminderStatus: "pending",
    reminderMessage: null,
    autoGenerated: false,
    createdAt: `${addDaysAthensCalendar(today, -3)}T10:00:00.000Z`,
    updatedAt: `${today}T08:00:00.000Z`,
  }),
  taskBase({
    id: "task-demo-2",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000103",
    childLabel: "Τσίτσος Μ.",
    parentId: null,
    parentLabel: "Τσίτσου Ελένη",
    locationCode: "evosmos",
    staffMemberLabel: null,
    taskTypeCode: "payment_followup",
    taskTypeLabel: "Follow-up οικονομικής οφειλής",
    title: "Τηλεφωνική υπενθύμιση γονέα — υπόλοιπο",
    requestedByLabel: "Σύστημα",
    assignedToLabel: "Γραμματεία",
    priority: "urgent",
    status: "overdue",
    dueDate: addDaysAthensCalendar(today, -2),
    dueTime: null,
    followUpDate: today,
    linkedAppointmentId: null,
    linkedPaymentId: "pay-demo-2",
    linkedDiagnosisId: null,
    linkedReportId: null,
    linkedMeetingId: null,
    completionDate: null,
    outcome: null,
    notes: "Υπόλοιπο 120€ · 2η κλήση.",
    alertLevel: "red",
    reminderDate: today,
    reminderTime: "11:00",
    reminderStatus: "scheduled",
    reminderMessage: "Υπενθύμιση πληρωμής",
    autoGenerated: true,
    createdAt: `${addDaysAthensCalendar(today, -10)}T09:00:00.000Z`,
    updatedAt: `${today}T07:30:00.000Z`,
  }),
  taskBase({
    id: "task-demo-3",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000101",
    childLabel: "Παπαδόπουλος Ν.",
    parentId: null,
    parentLabel: "Παπαδόπουλος Γιώργος",
    locationCode: "nikaia",
    staffMemberLabel: "Λογοθεραπευτής Α.",
    taskTypeCode: "report_request",
    taskTypeLabel: "Αίτημα αναφοράς προόδου",
    title: "Παρακολούθηση αναφοράς προόδου",
    requestedByLabel: "Γονέας",
    assignedToLabel: "Γραμματεία",
    priority: "normal",
    status: "waiting_response",
    dueDate: addDaysAthensCalendar(today, 3),
    dueTime: null,
    followUpDate: null,
    linkedAppointmentId: null,
    linkedPaymentId: null,
    linkedDiagnosisId: null,
    linkedReportId: "rep-demo-1",
    linkedMeetingId: null,
    completionDate: null,
    outcome: null,
    notes: "Αναμονή από θεραπευτή.",
    alertLevel: "yellow",
    reminderDate: null,
    reminderTime: null,
    reminderStatus: "none",
    reminderMessage: null,
    autoGenerated: true,
    createdAt: `${addDaysAthensCalendar(today, -5)}T11:00:00.000Z`,
    updatedAt: `${addDaysAthensCalendar(today, -1)}T15:00:00.000Z`,
  }),
  taskBase({
    id: "task-demo-4",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000104",
    childLabel: "Φωτίου Κ.",
    parentId: null,
    parentLabel: "Φωτίου Σοφία",
    locationCode: "nikaia",
    staffMemberLabel: null,
    taskTypeCode: "diagnosis_followup",
    taskTypeLabel: "Follow-up γνωμάτευσης",
    title: "Ανανέωση παιδοψυχιατρικής γνωμάτευσης",
    requestedByLabel: "Σύστημα",
    assignedToLabel: "Γραμματεία",
    priority: "urgent",
    status: "in_progress",
    dueDate: addDaysAthensCalendar(today, 5),
    dueTime: null,
    followUpDate: addDaysAthensCalendar(today, 2),
    linkedAppointmentId: null,
    linkedPaymentId: null,
    linkedDiagnosisId: "diag-demo-2",
    linkedReportId: null,
    linkedMeetingId: null,
    completionDate: null,
    outcome: null,
    notes: "Έγγραφο έληξε — επικοινωνία με γιατρό.",
    alertLevel: "red",
    reminderDate: addDaysAthensCalendar(today, 1),
    reminderTime: "10:00",
    reminderStatus: "pending",
    reminderMessage: null,
    autoGenerated: true,
    createdAt: `${addDaysAthensCalendar(today, -14)}T08:00:00.000Z`,
    updatedAt: `${today}T09:15:00.000Z`,
  }),
  taskBase({
    id: "task-demo-5",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000101",
    childLabel: "Παπαδόπουλος Ν.",
    parentId: null,
    parentLabel: "Παπαδόπουλος Γιώργος",
    locationCode: "nikaia",
    staffMemberLabel: null,
    taskTypeCode: "call_parent",
    taskTypeLabel: "Τηλεφωνική επικοινωνία με γονέα",
    title: "Επιβεβαίωση ραντεβού αξιολόγησης",
    requestedByLabel: "Γραμματεία",
    assignedToLabel: "Υποδοχή Νίκαια",
    priority: "normal",
    status: "open",
    dueDate: today,
    dueTime: "16:30",
    followUpDate: null,
    linkedAppointmentId: "appt-demo-1",
    linkedPaymentId: null,
    linkedDiagnosisId: null,
    linkedReportId: null,
    linkedMeetingId: null,
    completionDate: null,
    outcome: null,
    notes: "",
    alertLevel: "yellow",
    reminderDate: today,
    reminderTime: "16:00",
    reminderStatus: "pending",
    reminderMessage: null,
    autoGenerated: false,
    createdAt: `${addDaysAthensCalendar(today, -1)}T12:00:00.000Z`,
    updatedAt: `${today}T06:00:00.000Z`,
  }),
  taskBase({
    id: "task-demo-6",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000102",
    childLabel: "Οικονομίδου Ε.",
    parentId: null,
    parentLabel: "Οικονομίδου Μαρία",
    locationCode: "evosmos",
    staffMemberLabel: null,
    taskTypeCode: "call_doctor",
    taskTypeLabel: "Τηλεφωνική επικοινωνία με γιατρό",
    title: "Αίτημα ενημέρωσης γνωμάτευσης",
    requestedByLabel: "Επόπτης",
    assignedToLabel: "Γραμματεία",
    priority: "high",
    status: "open",
    dueDate: addDaysAthensCalendar(today, 1),
    dueTime: "11:30",
    followUpDate: null,
    linkedAppointmentId: null,
    linkedPaymentId: null,
    linkedDiagnosisId: "diag-demo-1",
    linkedReportId: null,
    linkedMeetingId: null,
    completionDate: null,
    outcome: null,
    notes: "Συντονισμός με παιδοψυχίατρο.",
    alertLevel: "yellow",
    reminderDate: null,
    reminderTime: null,
    reminderStatus: "none",
    reminderMessage: null,
    autoGenerated: false,
    createdAt: `${addDaysAthensCalendar(today, -2)}T14:00:00.000Z`,
    updatedAt: `${addDaysAthensCalendar(today, -2)}T14:00:00.000Z`,
  }),
  taskBase({
    id: "task-demo-7",
    organizationId: ORG,
    childId: null,
    childLabel: null,
    parentId: null,
    parentLabel: null,
    locationCode: "nikaia",
    staffMemberLabel: "Επόπτης Λογοθεραπείας",
    taskTypeCode: "internal_meeting",
    taskTypeLabel: "Προγραμματισμός εσωτερικής συνάντησης",
    title: "Συνάντηση ομάδας — Εύοσμος",
    requestedByLabel: "Διοίκηση",
    assignedToLabel: "Επόπτης",
    priority: "low",
    status: "open",
    dueDate: addDaysAthensCalendar(today, 4),
    dueTime: "13:00",
    followUpDate: null,
    linkedAppointmentId: null,
    linkedPaymentId: null,
    linkedDiagnosisId: null,
    linkedReportId: null,
    linkedMeetingId: null,
    completionDate: null,
    outcome: null,
    notes: "Αίθουσα 2",
    alertLevel: "green",
    reminderDate: null,
    reminderTime: null,
    reminderStatus: "none",
    reminderMessage: null,
    autoGenerated: false,
    createdAt: `${addDaysAthensCalendar(today, -7)}T10:00:00.000Z`,
    updatedAt: `${addDaysAthensCalendar(today, -7)}T10:00:00.000Z`,
  }),
  taskBase({
    id: "task-demo-8",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000103",
    childLabel: "Τσίτσος Μ.",
    parentId: null,
    parentLabel: "Τσίτσου Ελένη",
    locationCode: "evosmos",
    staffMemberLabel: null,
    taskTypeCode: "no_show_followup",
    taskTypeLabel: "Follow-up μη προσέλευσης",
    title: "Μη προσέλευση — επαναπρογραμματισμός",
    requestedByLabel: "Σύστημα",
    assignedToLabel: "Γραμματεία",
    priority: "high",
    status: "completed",
    dueDate: addDaysAthensCalendar(today, -3),
    dueTime: null,
    followUpDate: null,
    linkedAppointmentId: "appt-demo-3",
    linkedPaymentId: null,
    linkedDiagnosisId: null,
    linkedReportId: null,
    linkedMeetingId: null,
    completionDate: addDaysAthensCalendar(today, -2),
    outcome: "Νέο ραντεβού 20/05",
    notes: "Ο γονέας ενημερώθηκε.",
    alertLevel: "green",
    reminderDate: null,
    reminderTime: null,
    reminderStatus: "sent",
    reminderMessage: null,
    autoGenerated: true,
    createdAt: `${addDaysAthensCalendar(today, -4)}T16:00:00.000Z`,
    updatedAt: `${addDaysAthensCalendar(today, -2)}T11:00:00.000Z`,
  }),
];

export const SECRETARY_DEMO_DIAGNOSES: DiagnosisDocument[] = [
  {
    id: "diag-demo-1",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000101",
    childLabel: "Παπαδόπουλος Ν.",
    parentLabel: "Παπαδόπουλος Γιώργος",
    locationCode: "nikaia",
    documentTypeCode: "kedasy",
    documentType: "Γνωμάτευση ΚΕΔΑΣΥ",
    diagnosisDescription: "Διαταραχή προσοχής — ΦΕΚ",
    issuingAuthority: "ΔΑΔΑ Νίκαιας",
    doctorSpecialty: "Ψυχολόγος",
    issueDate: addDaysAthensCalendar(today, -300),
    expiryDate: addDaysAthensCalendar(today, 25),
    renewalRequired: true,
    renewalProcessStarted: false,
    renewalFollowUpDate: null,
    responsiblePersonLabel: "Γραμματεία",
    status: "expiring_30",
    alertLevel: "yellow",
    daysUntilExpiry: 25,
    notes: "",
    fileName: "fek-papadopoulos.pdf",
    fileUploadedAt: addDaysAthensCalendar(today, -280),
    archived: false,
    renewedAt: null,
    createdByLabel: "Γραμματεία",
    createdAt: `${addDaysAthensCalendar(today, -300)}T10:00:00.000Z`,
    updatedByLabel: "Γραμματεία",
    updatedAt: `${today}T08:00:00.000Z`,
  },
  {
    id: "diag-demo-2",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000104",
    childLabel: "Φωτίου Κ.",
    parentLabel: "Φωτίου Μαρία",
    locationCode: "evosmos",
    documentTypeCode: "child_psychiatrist",
    documentType: "Γνωμάτευση Παιδοψυχιάτρου",
    diagnosisDescription: "Αυτισμός — ανανέωση απαιτείται",
    issuingAuthority: "Νοσοκομείο Παίδων",
    doctorSpecialty: "Παιδοψυχίατρος",
    issueDate: addDaysAthensCalendar(today, -400),
    expiryDate: addDaysAthensCalendar(today, -5),
    renewalRequired: true,
    renewalProcessStarted: false,
    renewalFollowUpDate: null,
    responsiblePersonLabel: "Γραμματεία",
    status: "expired",
    alertLevel: "red",
    daysUntilExpiry: -5,
    notes: "Αναμονή νέου εγγράφου από γονέα",
    fileName: null,
    fileUploadedAt: null,
    archived: false,
    renewedAt: null,
    createdByLabel: "Γραμματεία",
    createdAt: `${addDaysAthensCalendar(today, -400)}T10:00:00.000Z`,
    updatedByLabel: null,
    updatedAt: `${addDaysAthensCalendar(today, -10)}T10:00:00.000Z`,
  },
  {
    id: "diag-demo-3",
    organizationId: ORG,
    childId: "20000000-0000-4000-8000-000000000103",
    childLabel: "Τσίτσος Μ.",
    parentLabel: "Τσίτσου Ελένη",
    locationCode: "nikaia",
    documentTypeCode: "developmental",
    documentType: "Γνωμάτευση Αναπτυξιολόγου",
    diagnosisDescription: "Αναπτυξιακή καθυστέρηση",
    issuingAuthority: "Ιδιώτης ιατρός",
    doctorSpecialty: "Αναπτυξιολόγος",
    issueDate: addDaysAthensCalendar(today, -200),
    expiryDate: addDaysAthensCalendar(today, 55),
    renewalRequired: true,
    renewalProcessStarted: true,
    renewalFollowUpDate: addDaysAthensCalendar(today, 10),
    responsiblePersonLabel: "Γραμματεία",
    status: "renewal_in_progress",
    alertLevel: "yellow",
    daysUntilExpiry: 55,
    notes: "Ξεκίνησε διαδικασία ανανέωσης",
    fileName: "anaptixiologos-tsitsos.pdf",
    fileUploadedAt: addDaysAthensCalendar(today, -195),
    archived: false,
    renewedAt: null,
    createdByLabel: "Γραμματεία",
    createdAt: `${addDaysAthensCalendar(today, -200)}T10:00:00.000Z`,
    updatedByLabel: "Γραμματεία",
    updatedAt: `${today}T09:00:00.000Z`,
  },
];

export const SECRETARY_DEMO_COMMUNICATIONS: CommunicationLog[] = [
  {
    id: "comm-demo-1",
    organizationId: ORG,
    locationCode: "nikaia",
    childId: "20000000-0000-4000-8000-000000000101",
    childLabel: "Παπαδόπουλος Ν.",
    parentId: null,
    parentLabel: "Παπαδόπουλος Γιώργος",
    contactPerson: "Καθηγήτρια Τάξης",
    contactRole: "teacher",
    contactPhone: null,
    contactEmail: null,
    communicationTypeCode: "school_call",
    communicationTypeLabel: "Τηλεφωνική επικοινωνία με σχολείο",
    reasonCode: "school_request",
    reason: "Αίτημα σχολείου",
    summary: "Ζητήθηκε παράλληλη στήριξη — αποστολή email.",
    outcome: null,
    nextActionRequired: true,
    nextAction: "Αποστολή εγγράφου",
    followUpDate: addDaysAthensCalendar(today, 7),
    followUpTime: "10:00",
    priority: "normal",
    status: "needs_followup",
    responsiblePersonLabel: "Γραμματεία",
    linkedTaskId: null,
    linkedAppointmentId: null,
    linkedPaymentId: null,
    linkedDiagnosisId: null,
    linkedReportId: null,
    linkedMeetingId: null,
    occurredAt: `${today}T09:30:00.000Z`,
    communicationDate: today,
    communicationTime: "11:30",
    createdByLabel: "Γραμματεία",
    createdAt: `${today}T09:30:00.000Z`,
    autoGenerated: false,
    alertLevel: "yellow",
  },
  {
    id: "comm-demo-2",
    organizationId: ORG,
    locationCode: "evosmos",
    childId: "20000000-0000-4000-8000-000000000103",
    childLabel: "Τσίτσος Μ.",
    parentId: null,
    parentLabel: "Τσίτσου Ελένη",
    contactPerson: "Τσίτσου Ελένη",
    contactRole: "parent",
    contactPhone: "6900000000",
    contactEmail: null,
    communicationTypeCode: "parent_call",
    communicationTypeLabel: "Τηλεφωνική επικοινωνία με γονέα",
    reasonCode: "payment_issue",
    reason: "Θέμα πληρωμής",
    summary: "Υπενθύμιση υπολοίπου 120€ — συμφώνησε πληρωμή έως Παρασκευή.",
    outcome: "Θα καταβάλει 60€",
    nextActionRequired: true,
    nextAction: "Επιβεβαίωση πληρωμής",
    followUpDate: addDaysAthensCalendar(today, 2),
    followUpTime: null,
    priority: "high",
    status: "waiting_response",
    responsiblePersonLabel: "Γραμματεία",
    linkedTaskId: "task-demo-2",
    linkedAppointmentId: null,
    linkedPaymentId: "pay-demo-2",
    linkedDiagnosisId: null,
    linkedReportId: null,
    linkedMeetingId: null,
    occurredAt: `${today}T14:00:00.000Z`,
    communicationDate: today,
    communicationTime: "16:00",
    createdByLabel: "Γραμματεία",
    createdAt: `${today}T14:00:00.000Z`,
    autoGenerated: false,
    alertLevel: "yellow",
  },
  {
    id: "comm-demo-3",
    organizationId: ORG,
    locationCode: "nikaia",
    childId: "20000000-0000-4000-8000-000000000104",
    childLabel: "Φωτίου Κ.",
    parentId: null,
    parentLabel: "Φωτίου Σοφία",
    contactPerson: "Παιδοψυχίατρος Δρ. Α.",
    contactRole: "doctor",
    contactPhone: null,
    contactEmail: "doctor@example.com",
    communicationTypeCode: "doctor_call",
    communicationTypeLabel: "Τηλεφωνική επικοινωνία με γιατρό",
    reasonCode: "diagnosis_issue",
    reason: "Θέμα γνωμάτευσης",
    summary: "Ζητήθηκε νέο έγγραφο — αναμονή αποστολής.",
    outcome: null,
    nextActionRequired: true,
    nextAction: "Follow-up σε 5 ημέρες",
    followUpDate: addDaysAthensCalendar(today, -1),
    followUpTime: null,
    priority: "urgent",
    status: "overdue_followup",
    responsiblePersonLabel: "Γραμματεία",
    linkedTaskId: null,
    linkedAppointmentId: null,
    linkedPaymentId: null,
    linkedDiagnosisId: "diag-demo-2",
    linkedReportId: null,
    linkedMeetingId: null,
    occurredAt: `${addDaysAthensCalendar(today, -3)}T10:00:00.000Z`,
    communicationDate: addDaysAthensCalendar(today, -3),
    communicationTime: "12:00",
    createdByLabel: "Γραμματεία",
    createdAt: `${addDaysAthensCalendar(today, -3)}T10:00:00.000Z`,
    autoGenerated: false,
    alertLevel: "red",
  },
  {
    id: "comm-demo-4",
    organizationId: ORG,
    locationCode: "nikaia",
    childId: "20000000-0000-4000-8000-000000000102",
    childLabel: "Οικονομίδου Ε.",
    parentId: null,
    parentLabel: "Οικονομίδου Μαρία",
    contactPerson: "Οικονομίδου Μαρία",
    contactRole: "parent",
    contactPhone: "6911111111",
    contactEmail: "parent@example.com",
    communicationTypeCode: "sms",
    communicationTypeLabel: "SMS",
    reasonCode: "parent_update",
    reason: "Ενημέρωση γονέα",
    summary: "Αποστολή SMS υπενθύμισης ραντεβού.",
    outcome: "Απεστάλη",
    nextActionRequired: false,
    nextAction: null,
    followUpDate: null,
    followUpTime: null,
    priority: "low",
    status: "completed",
    responsiblePersonLabel: "Γραμματεία",
    linkedTaskId: null,
    linkedAppointmentId: "appt-demo-1",
    linkedPaymentId: null,
    linkedDiagnosisId: null,
    linkedReportId: null,
    linkedMeetingId: null,
    occurredAt: `${addDaysAthensCalendar(today, -1)}T08:00:00.000Z`,
    communicationDate: addDaysAthensCalendar(today, -1),
    communicationTime: "10:00",
    createdByLabel: "Σύστημα (υπενθύμιση)",
    createdAt: `${addDaysAthensCalendar(today, -1)}T08:00:00.000Z`,
    autoGenerated: true,
    alertLevel: "green",
  },
];

export const SECRETARY_DEMO_REPORTS: ReportRequest[] = [
  {
    id: "rep-demo-1",
    childId: "20000000-0000-4000-8000-000000000102",
    childLabel: "Οικονομίδου Ε.",
    parentLabel: "Οικονομίδου Μ.",
    locationCode: "nikaia" as const,
    reportTypeCode: "progress",
    reportTypeLabel: "Αναφορά προόδου",
    requestedBy: "Οικονομίδου Μ.",
    requestSource: "parent" as const,
    status: "draft_in_progress" as const,
    requestDate: addDaysAthensCalendar(today, -10),
    dueDate: addDaysAthensCalendar(today, 3),
    priority: "high" as const,
    purpose: "Ενημέρωση γονέα για πρόοδο λογοθεραπείας",
    assignedTherapistLabels: ["Βασιλείου Ν."],
    assignedTherapistLabel: "Βασιλείου Ν.",
    assignedSupervisorLabel: "Επόπτης Λογ.",
    clinicalDirectorApprovalRequired: false,
    notes: "Προτεραιότητα από γονέα",
  },
  {
    id: "rep-demo-2",
    childId: "20000000-0000-4000-8000-000000000101",
    childLabel: "Παπαδόπουλος Ι.",
    parentLabel: "Παπαδόπουλος Κ.",
    locationCode: "evosmos" as const,
    reportTypeCode: "school",
    reportTypeLabel: "Αναφορά προς σχολείο",
    requestedBy: "Δάσκαλος 3ου Δημοτικού",
    requestSource: "school" as const,
    status: "supervisor_review" as const,
    requestDate: addDaysAthensCalendar(today, -20),
    dueDate: addDaysAthensCalendar(today, -2),
    priority: "urgent" as const,
    purpose: "Αίτημα σχολείου για συντονισμό",
    assignedTherapistLabels: ["Ζωγράφου Σ."],
    assignedTherapistLabel: "Ζωγράφου Σ.",
    assignedSupervisorLabel: "Επόπτης Εργ.",
    clinicalDirectorApprovalRequired: false,
    supervisorReviewStartedAt: addDaysAthensCalendar(today, -5) + "T10:00:00.000Z",
    notes: "",
  },
  {
    id: "rep-demo-3",
    childId: "20000000-0000-4000-8000-000000000102",
    childLabel: "Οικονομίδου Ε.",
    parentLabel: "Οικονομίδου Μ.",
    locationCode: "nikaia" as const,
    reportTypeCode: "evaluation",
    reportTypeLabel: "Αξιολογητική έκθεση",
    requestedBy: "Διοίκηση",
    requestSource: "management" as const,
    status: "ready_for_delivery" as const,
    requestDate: addDaysAthensCalendar(today, -30),
    dueDate: addDaysAthensCalendar(today, 5),
    priority: "normal" as const,
    purpose: "Πλήρης αξιολογητική για ΚΕΔΑΣΥ",
    assignedTherapistLabels: ["Βασιλείου Ν.", "Παπαδάκη Μ."],
    assignedTherapistLabel: "Βασιλείου Ν.",
    assignedSupervisorLabel: "Επόπτης Λογ.",
    clinicalDirectorApprovalRequired: true,
    finalFileName: "axiologisi-oikonomidou-final.pdf",
    notes: "Εγκρίθηκε από ΚΔ",
  },
  {
    id: "rep-demo-4",
    childId: "20000000-0000-4000-8000-000000000101",
    childLabel: "Παπαδόπουλος Ι.",
    parentLabel: "Παπαδόπουλος Κ.",
    locationCode: "evosmos" as const,
    reportTypeCode: "parent_brief",
    reportTypeLabel: "Σύντομη ενημερωτική αναφορά γονέα",
    requestedBy: "Γραμματεία",
    requestSource: "parent" as const,
    status: "delivered" as const,
    requestDate: addDaysAthensCalendar(today, -45),
    dueDate: addDaysAthensCalendar(today, -30),
    deliveryDate: addDaysAthensCalendar(today, -28),
    deliveredTo: "Παπαδόπουλος Κ.",
    deliveryMethod: "email" as const,
    priority: "normal" as const,
    purpose: "Τριμηνιαία ενημέρωση",
    assignedTherapistLabels: ["Ζωγράφου Σ."],
    assignedTherapistLabel: "Ζωγράφου Σ.",
    assignedSupervisorLabel: "Επόπτης Εργ.",
    clinicalDirectorApprovalRequired: false,
    finalFileName: "parent-brief-papadopoulos.pdf",
    notes: "",
  },
].map((r) =>
  enrichReport(
    normalizeReportRequest(
      r as Partial<ReportRequest> & Pick<ReportRequest, "id" | "childId" | "childLabel">,
      today
    ),
    today
  )
);

export const SECRETARY_DEMO_MEETINGS: InternalMeeting[] = [
  {
    id: "meet-demo-1",
    meetingTypeCode: "group_supervision",
    meetingTypeLabel: "Ομαδική εποπτεία",
    childId: null,
    childLabel: null,
    agenda: "Εβδομαδιαία εποπτεία ομάδας λογοθεραπείας",
    startsAt: athensSlot(today, 19, 0, 60).startsAt,
    endsAt: athensSlot(today, 19, 0, 60).endsAt,
    locationCode: "nikaia",
    status: "scheduled",
    attendeeLabels: ["Επόπτης Λογ.", "Ζωγράφου Σ.", "Παπαδάκη Μ."],
  },
  {
    id: "meet-demo-2",
    meetingTypeCode: "case_supervision",
    meetingTypeLabel: "Εποπτεία περιστατικού",
    childId: "20000000-0000-4000-8000-000000000101",
    childLabel: "Παπαδόπουλος Ν.",
    agenda: "Περιστατικό — πρόοδος & στόχοι",
    startsAt: athensSlot(addDaysAthensCalendar(today, 2), 11, 0, 45).startsAt,
    endsAt: athensSlot(addDaysAthensCalendar(today, 2), 11, 0, 45).endsAt,
    locationCode: "evosmos",
    status: "confirmed",
    attendeeLabels: ["Επόπτης Λογ.", "Βασιλείου Ν."],
  },
  {
    id: "meet-demo-3",
    meetingTypeCode: "emergency",
    meetingTypeLabel: "Έκτακτη συνάντηση",
    childId: "20000000-0000-4000-8000-000000000102",
    childLabel: "Γεωργίου Μ.",
    agenda: "Έκτακτο θέμα συμπεριφοράς — συντονισμός ομάδας",
    startsAt: athensSlot(today, 14, 30, 30).startsAt,
    endsAt: athensSlot(today, 14, 30, 30).endsAt,
    locationCode: "online",
    status: "scheduled",
    attendeeLabels: ["Κλινικός Διευθυντής", "Επόπτης Ψυχ.", "Γραμματεία"],
  },
  {
    id: "meet-demo-4",
    meetingTypeCode: "admin_internal",
    meetingTypeLabel: "Εσωτερική διοικητική συνάντηση",
    childId: null,
    childLabel: null,
    agenda: "Λειτουργικά θέματα εβδομάδας",
    startsAt: athensSlot(addDaysAthensCalendar(today, -3), 10, 0, 45).startsAt,
    endsAt: athensSlot(addDaysAthensCalendar(today, -3), 10, 0, 45).endsAt,
    locationCode: "nikaia",
    status: "completed",
    attendeeLabels: ["Γενικός Διευθυντής", "Γραμματεία"],
  },
];

export const SECRETARY_DEMO_INTAKES: ClientIntake[] = [
  {
    id: "intake-demo-1",
    organizationId: ORG,
    childId: null,
    leadStatus: "new_interest",
    completeness: "complete",
    childFirstName: "Νίκος",
    childLastName: "Αλεξίου",
    dateOfBirth: "2018-03-12",
    parentNames: "Αλεξίου Μαρία",
    parentPrimaryName: "Αλεξίου Μαρία",
    parentSecondaryName: null,
    phonePrimary: "6912345678",
    phoneSecondary: null,
    email: "maria@example.com",
    addressFull: null,
    addressArea: "Δραπετσώνα",
    schoolName: "2ο Δημοτικό",
    schoolGrade: "Α'",
    mainReason: "Δυσκολίες ομιλίας",
    referralSource: "Γονέας",
    existingDiagnosis: null,
    hasExistingDiagnosis: false,
    diagnosisDocumentExists: false,
    multipleDiagnosisDocuments: false,
    diagnosisType: null,
    diagnosisExpiryDate: null,
    doctorName: null,
    currentTherapies: null,
    previousTherapies: null,
    parentConcerns: "Καθυστέρηση λόγου",
    preferredTimes: "Απόγευμα",
    interestedServices: "Λογοθεραπεία",
    urgencyLevel: "normal",
    notes: "",
    gdprConsent: true,
    consentPhone: true,
    consentSms: true,
    consentEmail: true,
    consentViber: false,
    consentWhatsapp: false,
    schoolDoctorContactConsent: false,
    consentExternalProfessionals: false,
    followUpReminderAt: addDaysAthensCalendar(today, 3) + "T10:00:00.000Z",
    submittedAt: `${today}T08:00:00.000Z`,
    updatedAt: `${today}T08:00:00.000Z`,
  },
];

export const SECRETARY_DEMO_PROGRAMS: CaseProgram[] = [
  {
    id: "prog-demo-1",
    childId: "20000000-0000-4000-8000-000000000101",
    childLabel: "Παπαδόπουλος Ν.",
    serviceTypeCode: "speech",
    serviceTypeLabel: "Λογοθεραπεία",
    frequencyPerWeek: 2,
    startDate: addDaysAthensCalendar(today, -60),
    endDate: null,
    therapistLabels: ["Δρ. Ανδρέου (ΚΔ)"],
    paymentPackageLabel: "Μηνιαίο πακέτο 8 συνεδρίες",
    status: "active",
  },
  {
    id: "prog-demo-2",
    childId: "20000000-0000-4000-8000-000000000102",
    childLabel: "Οικονομίδου Ε.",
    serviceTypeCode: "psych",
    serviceTypeLabel: "Ψυχολογική υποστήριξη",
    frequencyPerWeek: 1,
    startDate: addDaysAthensCalendar(today, -14),
    endDate: null,
    therapistLabels: ["Γεωργίου Ε. (Ψυχ.)"],
    paymentPackageLabel: null,
    status: "paused",
  },
];

export function buildSecretaryDemoDashboard(): SecretaryDashboardData {
  const conflictCount = detectAppointmentConflicts(SECRETARY_DEMO_APPOINTMENTS).filter(
    (c) => c.alertLevel === "red"
  ).length;
  const todayAppts = SECRETARY_DEMO_APPOINTMENTS.filter((a) => appointmentYmdAthens(a) === today);

  return {
    kpis: [
      { id: "today_appts", label: "Σημερινά ραντεβού", value: todayAppts.length, helper: "Όλοι οι τύποι", alertLevel: "green", href: "/secretary/schedule" },
      { id: "pending_eval", label: "Εκκρεμείς αξιολογήσεις", value: 2, helper: "Προς προγραμματισμό", alertLevel: "yellow", href: "/secretary/schedule?type=evaluation" },
      { id: "pending_intake", label: "Λήψη ιστορικού / ενημέρωση", value: 3, helper: "Εκκρεμεί ραντεβού", alertLevel: "yellow", href: "/secretary/schedule" },
      { id: "new_inquiries", label: "Νέα αιτήματα", value: SECRETARY_DEMO_INTAKES.length, helper: "Φόρμες intake", alertLevel: "yellow", href: "/secretary/new-case" },
      { id: "unpaid", label: "Ανεξόφλητα", value: 4, helper: "Τρέχον μήνα", alertLevel: "yellow", href: "/secretary/payments" },
      { id: "overdue_pay", label: "Καθυστερημένα", value: 2, helper: "Χρειάζεται ενέργεια", alertLevel: "red", href: "/secretary/payments?filter=overdue" },
      { id: "due_soon_pay", label: "Πληρωμές σύντομα", value: 3, helper: "Εντός 7 ημερών", alertLevel: "yellow", href: "/secretary/payments" },
      { id: "comm_pending", label: "Επικοινωνίες", value: 5, helper: "Ανοιχτές ενέργειες", alertLevel: "yellow", href: "/secretary/communications" },
      { id: "reports_pending", label: "Αναφορές", value: 2, helper: "Σε εξέλιξη", alertLevel: "yellow", href: "/secretary/reports" },
      { id: "diag_expiring", label: "Διαγνώσεις λήγουν", value: 3, helper: "Εντός 30 ημερών", alertLevel: "yellow", href: "/secretary/diagnoses" },
      { id: "urgent_tasks", label: "Επείγοντα", value: 1, helper: "Ανοιχτές εργασίες", alertLevel: "red", href: "/secretary/tasks" },
      { id: "conflicts", label: "Σύγκρουση προγράμματος", value: conflictCount, helper: "Απαιτεί διόρθωση", alertLevel: conflictCount > 0 ? "red" : "green", href: "/secretary/schedule" },
    ],
    urgentAlerts: [
      { id: "a1", title: "Καθυστερημένη πληρωμή", detail: "Τσίτσος Μ. — 180€ υπόλοιπο", alertLevel: "red", href: "/secretary/payments" },
      { id: "a2", title: "Ληγμένη διάγνωση", detail: "Φωτίου Κ. — ανανέωση άμεσα", alertLevel: "red", href: "/secretary/diagnoses" },
      { id: "a3", title: "Σύγκρουση προγράμματος", detail: "Διπλή κράτηση Αίθ. 1 σήμερα 16:00", alertLevel: "red", href: "/secretary/schedule" },
    ],
    todayAppointments: todayAppts.length > 0 ? todayAppts : SECRETARY_DEMO_APPOINTMENTS.slice(0, 4),
  };
}
