import type { SecretaryMeeting } from "@/lib/secretary/types";
import { createCommunicationDraft } from "@/lib/secretary/communications/store";
import { upsertCommunication } from "@/lib/secretary/communications/store";

function baseLog(
  meeting: SecretaryMeeting,
  todayYmd: string,
  idSuffix: string,
  reason: string,
  summary: string
) {
  return createCommunicationDraft(
    {
      id: `comm-meet-${meeting.id}-${idSuffix}`,
      childId: meeting.childId,
      childLabel: meeting.childLabel,
      parentLabel: meeting.parentLabel,
      contactPerson: meeting.organizerLabel,
      contactRole: "staff",
      communicationTypeCode: "supervisor_call",
      communicationTypeLabel: "Εσωτερική καταγραφή συνάντησης",
      reasonCode: "prior_followup",
      reason,
      summary,
      status: "completed",
      nextActionRequired: false,
      priority: meeting.isEmergency ? "urgent" : "normal",
      autoGenerated: true,
      createdByLabel: "Σύστημα (συνάντηση)",
      linkedMeetingId: meeting.id,
    },
    todayYmd
  );
}

export function autoLogMeetingScheduled(meeting: SecretaryMeeting, todayYmd: string): void {
  upsertCommunication(
    baseLog(
      meeting,
      todayYmd,
      "scheduled",
      `Προγραμματισμός: ${meeting.meetingTypeLabel}`,
      `${meeting.title} · ${meeting.meetingDate} ${meeting.startTime} · ${meeting.participants.join(", ")}`
    ),
    todayYmd
  );
}

export function autoLogMeetingCancelled(meeting: SecretaryMeeting, todayYmd: string): void {
  upsertCommunication(
    baseLog(
      meeting,
      todayYmd,
      "cancelled",
      `Ακύρωση συνάντησης: ${meeting.meetingTypeLabel}`,
      `Ακυρώθηκε: ${meeting.title} (${meeting.meetingDate} ${meeting.startTime})`
    ),
    todayYmd
  );
}

export function autoLogMeetingRescheduled(
  meeting: SecretaryMeeting,
  previousDate: string,
  todayYmd: string
): void {
  upsertCommunication(
    baseLog(
      meeting,
      todayYmd,
      "rescheduled",
      `Αναβολή συνάντησης: ${meeting.meetingTypeLabel}`,
      `Αναβλήθηκε από ${previousDate} σε ${meeting.meetingDate} ${meeting.startTime} — ${meeting.title}`
    ),
    todayYmd
  );
}

export function autoLogMeetingReminderSent(meeting: SecretaryMeeting, channel: string, todayYmd: string): void {
  upsertCommunication(
    baseLog(
      meeting,
      todayYmd,
      `reminder-${channel}`,
      `Υπενθύμιση συνάντησης (${channel})`,
      `Υπενθύμιση για ${meeting.title} · ${meeting.meetingDate} ${meeting.startTime}`
    ),
    todayYmd
  );
}
