import { addDaysAthensCalendar } from "@/lib/schedule/athens-civil";
import type { MeetingDecision, SecretaryMeeting, TaskPriority } from "@/lib/secretary/types";
import { createTaskDraft, getAllTasks } from "@/lib/secretary/tasks/store";
import { taskTypeByCode } from "@/lib/secretary/tasks/catalog";
import { isEmergencyMeetingType } from "./catalog";

function findMeetingTask(meetingId: string, suffix: string, todayYmd: string) {
  return getAllTasks(todayYmd).find(
    (t) =>
      t.linkedMeetingId === meetingId &&
      t.notes.includes(`meeting:${suffix}`) &&
      !["completed", "cancelled"].includes(t.status)
  );
}

function taskTypeForMeeting(m: SecretaryMeeting): string {
  if (m.meetingTypeCode === "parent") return "parent_meeting_followup";
  if (m.meetingTypeCode === "school") return "school_meeting_followup";
  if (["individual_supervision", "group_supervision", "case_supervision"].includes(m.meetingTypeCode))
    return "supervision_followup";
  if (m.isEmergency) return "management_review";
  if (m.meetingTypeCode === "performance_review") return "therapist_action_plan";
  return "meeting_followup";
}

function createMeetingTask(
  m: SecretaryMeeting,
  suffix: string,
  todayYmd: string,
  title: string,
  dueDate: string,
  priority: TaskPriority,
  assignee: string,
  taskTypeCode?: string
): void {
  if (findMeetingTask(m.id, suffix, todayYmd)) return;
  if (m.archived || m.status === "cancelled") return;
  const code = taskTypeCode ?? taskTypeForMeeting(m);
  createTaskDraft(
    {
      taskTypeCode: code,
      taskTypeLabel: taskTypeByCode(code)?.labelEl ?? title,
      title,
      childId: m.childId,
      childLabel: m.childLabel,
      parentLabel: m.parentLabel,
      locationCode: m.locationCode,
      linkedMeetingId: m.id,
      assignedToLabel: assignee,
      priority,
      dueDate,
      notes: `meeting:${suffix} · ${m.title}`,
      autoGenerated: true,
    },
    todayYmd
  );
}

function syncDecisionTask(
  m: SecretaryMeeting,
  d: MeetingDecision,
  todayYmd: string
): void {
  if (!d.responsiblePersonLabel || !d.dueDate) return;
  if (d.linkedTaskId) return;
  if (["completed", "cancelled"].includes(d.status)) return;

  createTaskDraft(
    {
      taskTypeCode: "decision_action",
      taskTypeLabel: "Ενέργεια από απόφαση",
      title: `Απόφαση: ${d.text.slice(0, 80)}`,
      childId: d.childId ?? m.childId,
      childLabel: d.childLabel ?? m.childLabel,
      parentLabel: m.parentLabel,
      locationCode: m.locationCode,
      linkedMeetingId: m.id,
      assignedToLabel: d.responsiblePersonLabel,
      priority: d.dueDate < todayYmd ? "urgent" : "normal",
      dueDate: d.dueDate,
      notes: `meeting:decision:${d.id}`,
      autoGenerated: true,
    },
    todayYmd
  );
}

export function syncAutoTasksFromMeeting(m: SecretaryMeeting, todayYmd: string): void {
  if (m.archived || m.status === "cancelled") return;

  if (m.minutesMissing && ["completed", "needs_minutes"].includes(m.status)) {
    createMeetingTask(
      m,
      "minutes",
      todayYmd,
      `Πρακτικά συνάντησης — ${m.title}`,
      addDaysAthensCalendar(todayYmd, 3),
      "high",
      m.organizerLabel
    );
  }

  if (m.followUpRequired || m.status === "needs_followup") {
    createMeetingTask(
      m,
      "followup",
      todayYmd,
      `Follow-up συνάντησης — ${m.title}`,
      addDaysAthensCalendar(todayYmd, 7),
      m.priority === "urgent" ? "urgent" : "normal",
      m.organizerLabel
    );
  }

  if (isEmergencyMeetingType(m.meetingTypeCode) && m.status !== "completed") {
    createMeetingTask(
      m,
      "emergency",
      todayYmd,
      `Έκτακτη συνάντηση — ${m.title}`,
      todayYmd,
      "urgent",
      "Γενικός Διευθυντής",
      "management_review"
    );
  }

  if (m.minutes?.therapistActionPlan?.trim()) {
    createMeetingTask(
      m,
      "action_plan",
      todayYmd,
      `Action plan — ${m.staffMemberLabel ?? m.title}`,
      addDaysAthensCalendar(todayYmd, 14),
      "high",
      m.staffMemberLabel ?? "Επόπτης",
      "therapist_action_plan"
    );
  }

  for (const d of m.decisions) {
    syncDecisionTask(m, d, todayYmd);
  }
}
